:experimental:
// enable 'kbd:[x]' macro

== Machine Language Entry Points

Here is a listing of ML modules and their entry points.

====
NOTE: This section is currently undergoing research.
====

=== Protocols [[protocols]]

`&,16,4,_x_`: `getflag`

`sub.protos`: This returns the value of `defflag` from the protocol.
Its purpose is currently unknown.

`&,16,5,_x_`: `getflag`

This sets the value of `defflag` from the protocol.
Its purpose is currently unknown.

==== `++ index`

This module handles the `u.config` (user log) and `u.weedinfo` (user weed info) files.

[%header]
[%autowidth]
|===
| Function  | Description | Entry | Exit
| `&,16[,0]`
| `find`--use a binary search to find `an$` in index

| LFN #2 for the REL file channel must be `open`

LFN #15 for the command channel must be `open`

`an$`=user name

| If `an$` is found: `a%`=value found, `b%`=the position found in

 If `an$` is not found: `a%`=`0`, `b%`=the position to insert to (probably the last record)

| `&,16,1`
| `loadindex`--load an index file into the index buffer
| `a$`="__drive__:__filename__", `dv%`=device #
| `a%`=number of entries in index

| `&,16,2`
| `saveindex`--save an index to disk
| `a$`="__drive__:__filename__", `dv%`=device #
| _n/a_

| `&,16,3`
| `makeindex`--clear the index buffer
| _n/a_
| _n/a_

| `&,16,4`
| `instindex`--insert a value into the index buffer
| `a%`=value, `b%`=position
| _n/a_

| `&,16,5`
| `deltindex`--delete a value from the index buffer
| `b%`=position
| _n/a_

| `&,16,6`
| `nextindex`--return the next value from the index buffer
| `b%`=current position
| `a%`=value at new position, `b%`=new position

| `&,16,7`
| `setcrskip`--set the # of carriage returns (CRs) to skip when reading data.

This allows fields other than the first one to be indexed.
| `a%`=number of CRs to skip
| _n/a_

| `&,16,8`
| `findindex`--find the first occurrence of the value given
| `a%`=value to find
| `b%`=0: not found, otherwise position found at
|===

////
;++ 4.docs ++ 4 (indexer) functions:

FIND      &,16
 Uses a binary search to find the string AN$ in the REL file.
   Entry: AN$=sting to find
          File 2 must be open to the REL file
          File 15 must be open to the command channel
   Exit:  if found then A%=value found, B%=position found
          if not found then A%=0, B%=position to insert

LOADINDX  &,16,1
 Load an index into the index buffer.
   Entry: A$=drive#+filename, DV%=device
   Exit:  A%=# of entries in index

SAVEINDX  &,16,2
 Save an index to disk.
   Entry: A$=drive#+filename, DV%=device

MAKEINDX  &,16,3
 This will clear the index buffer.

INSTINDX  &,16,4
 This will insert a value into the index buffer.
   Entry: A%=value, B%=position

DELTINDX  &,16,5
 This will delete a value from the index buffer.
   Entry: B%=position

NEXTINDX  &,16,6
 This will return the next value from the index buffer.
   Entry: B%=current position
   Exit:  A%=value at new position, B%=new position

SETCRSKP  &,16,7
 This will set the # of Carriage Returns to skip when reading data. This
 allows fields other than the first one to be indexed.
   Entry: A%=# of CRs

FINDINDX  &,16,8
 This will find the first occurance of the value given.
   Entry: A%=value to find
   Exit:  B%=position found at, or 0 if not found.
////

==== `++ post`

The `++ post` protocol supports querying which protocol is loaded in memory via `&,16,255`.
This returns the protocol number in `a%`.
This is useful to prevent unnecessary ``load``ing if the protocol is already in memory.

==== `++ punter`

[%header]
[%autowidth]
|===
| Function | Purpose | Returns
| `&,16,0` | multi-download | 
| `&,16,1` | multi-upload | 
| `&,16,2` | multi-download + header | 
| `&,16,3` | multi-upload   + header | 
| `&,16,4` | setflag | `a%`
| `&,16,5` | getflag | `a%`

(are these flags whether the protocol supports multi-file transfers?)
|===

==== `++ reader`

This module can display PRG files.

[%header]
[%autowidth]
|===
| Function | Purpose | Returns
| `&,16,0,_ll%_` | Detokenize BASIC file, use column width `ll%` | 
|===

==== Graphic Menu

The ML module `++ menu2` handles adding menu items, hotkeys, displaying the menu and passing the menu item selected back to BASIC.

`&,16,0`: 
Add menu item

_Parameters:_

`&,16,0,_?_,_menu%(field, record)_,_"hotkey(s)"_,_"prefix_text?"_,_"menu_item_text"_`

`?`: `42`: draw two-column menu

`menu%(_field,record_)`: struct to put menu text in

`hotkey(s)`: One (kbd:[B]) or two (kbd:[/B]) keys to type to select this menu item

`prefix_text`:

`menu_item_text`: Text the user sees for this menu item.

_Example:_

.i.GF: add menu item
[source]
3518 if pf>1 then:&,16,0,42,q%(0,n),"/B","Op ","Return to Previous Menu":n=n+1

.i.IM: add menu item
[source]
3008 &,16,.,34,m%(.,1),"A","","Macros Editor"

_Returns:_

`a%`: which item was selected

'''

`&,16,1`: Add string

_Parameters:_

Unknown.

'''

`&,16,2`: Use menu

_Parameters:_

 &,16,2, _?_, _menu%(field,record)_, _item_count?_, _?_, _?_, _menu_height?_, _?_, _?_, _?_

// #FIXME#

_Examples:_

.i.IM: Use menu
[source]
3350 &,16,2,34,m%(.,1),n,17,2,n/2+.5,2,6,.:lm=a%+1:&,70,.,n/2+8.5:&"{white}":return

_Returns:_

`a%`: item number selected

'''

`&,16,3`: ?

