:toc: left
:icons: font

// https://github.com/Pinacolada64/ImageBBS/blob/534f39f7cbe3f8c896725bc1db94fa23416ecacf/v2/docs/%26%20commands.txt

## Static Arrays (Structures) [[structures]]

_Structures_ (or _structs_) allow you to treat the memory used by arrays as blocks of memory.
You can store multiple types of data in this memory, and perform operations on the data using `&,60` and various sub-commands.
This is much faster than a BASIC `for...next` loop.

There are functions to:

* put and get strings, and Image-formatted 11-digit dates
* sort and filter data
* collect information from one structure, and put the results in another array
* load and save structures

#FIXME: more functions#

_Elements_ are the individual "`boxes`" in the array that data is held in.

Strings can be stored in either a floating point or integer array.
Two bytes per element of the string text can be stored per element of an integer array.


.Representation of Sample 2D Integer Array
[%autowidth]
|===
| `x%(0,0)` | `x%(0,1)` | `x%(0,2)`
| `x%(1,0)` | `x%(1,1)` | `x%(1,2)`
| `x%(2,0)` | `x%(2,1)` | `x%(2,2)`
|===

////
TODO: later
Let's write a BASIC program to fill and display the elements of an integer array, and then we'll show how to refer to the elements:

.Sample Array
#TODO: finish this#
```
10 print
20 end
```
////

It is suggested that you use numeric type arrays, since this will allow you to access the elements as numeric data, as well as put and get strings.

// TODO: can you use string arrays?

Floating point arrays (like `a()` or `b()`) use 5 bytes per element.
Integer arrays (like `a%()` or `b%()`) use 2 bytes per element.
When deciding to use structures, you should determine what types of data you will need to store, and how much memory that data will require.


====
As a running example, let`'s design a structure to hold a user’s ID#, handle, and password.
A module will be written to store, edit, and retrieve data to/from this structure.

* The ID is an integer type (never > 32767), requiring 2 bytes.
* The handle can be up to 20 characters.
* The password can be up to 15 characters.

Since the integers store in 2 bytes, the total number of bytes needed is 37 (2 + 20 + 15).
Thirty-seven bytes would require either:

* 19 integer elements (2 bytes per element &times; 19 elements  &equals; 38 bytes)

_or_

* 8 floating point elements (5 bytes per element &times; 8 elements  &equals; 40 bytes).

Now that you have the basic concept of the structure, let’s look in a little more detail.
Here is a byte-by-byte map of the structure we designed.

[%header]
[%autowidth]
.Sample Structure layout
|===
| Element Position | Byte Position | Data | Type | Bytes Used
| Element 0 | Bytes 00-01 | ID# | Integer | 2 bytes
| Element 1 | Bytes 02-21 | Handle | String | 20 bytes
| Element 11 | Bytes 22-36 | Password | String | 15 bytes
| Element 18½ | Byte 37 | _unused_ | _n/a_ | 1 byte
|===

// Representation of user data struct

.Structure Data Storage
[cols="12"]
[%autowidth]
|===
// 6 cells, cols 2-3, 4-5, 6-7, 8-9, 10-11 span
>|Element
^| `u%(0,0)`
^| `u%(0,1)`
^| `u%(0,2)`
^| `u%(0,3)`
^| `u%(0,4)`
^| `u%(0,5)`
^| `u%(0,6)`
^| `u%(0,7)`
^| `u%(0,8)`
^| `u%(0,9)`
^| `u%(0,10)`

>| Byte&nbsp;Pos
^| `00&nbsp;01`
^| `02&nbsp;03`
^| `04&nbsp;05`
^| `06&nbsp;07`
^| `08&nbsp;09`
^| `10&nbsp;11`
^| `12&nbsp;13`
^| `14&nbsp;15`
^| `16&nbsp;17`
^| `18&nbsp;19`
^| `20&nbsp;21`

>| Data
^| ID#
10+^| Handle _(20 bytes)_

>| Bytes
^| `0 1`
^| `P I`
^| `N A`
^| `C O`
^| `L A`
^| `D A`
^| _x x_
^| _x x_
^| _x x_
^| _x x_
^| _x x_
|===


[cols="10"]
[%autowidth]
|===
// 10 cells, cols 9-10 span
>|Element
^| `u%(0,11)`
^| `u%(0,12)`
^| `u%(0,13)`
^| `u%(0,14)`
^| `u%(0,15)`
^| `u%(0,16)`
^| `u%(0,17)`
2+^| `u%(0,18)`

>| Byte&nbsp;Pos
^| `22&nbsp;23`
^| `24&nbsp;25`
^| `26&nbsp;27`
^| `28&nbsp;29`
^| `30&nbsp;31`
^| `32&nbsp;33`
^| `34&nbsp;35`
^| `36`
^| `37`

>| Data
8+^| Password _(15 bytes)_
^| _unused_

>| Bytes
^| `P A`
^| `S S`
^| `W O`
^| `R D`
^| _x x_
^| _x x_
^| _x x_
^| _x_
^| _unused_
|===

TIP: Because the unused byte 37 is _not_ on an even element boundary (the previous element is an odd number of bytes), it cannot be used.

Since the ID# is an integer anyway, it would be best to use an integer array.
The definition would look like this:

 dim u%(18)

TIP: Remember that arrays start at element 0!
There are 19 bytes in this structure, 0-18.

Of course, you may want to store more than one of these structures in memory.
To do so, you would need a 2-dimensional array.  This would change the `dim` statement to:

 dim u%(18,x-1)

(Suppose that _x_ is the number of structures you want.)

====

// Ryan added this next bit, and changed "element number/byte number" to "record" and "field"

To refer to bytes in a structure:

* the first number in the array notation is the _record number_ (like a field of a record in a RELative file)
* the second number is the _field number_ (or _byte number_).

TIP: Record `0`, field `0` (_e.g._, `u%(0,0)`) is often used to hold the number of elements in the structure.

Now down to the important part: how to use all of this!
The structure system is called with either `&,60,_x_,...` or `&,68,_x_,...`.

There are currently 14 sub-functions supported by the structure routines.
They are documented below.

### Numeric Values and Structures

The array used with structures is either an integer or floating point type.
To put numeric values into--or get numeric values from--a structure requires no special structure calls.

// Is this supported?
// If you are using string arrays,
You may use code similar to the following examples:

.Get number from and put number into structure
[%header]
[%autowidth]
|===
| Get value | Put value
| `f=a%(3,3)` | `a%(3,3)=20`

//| `f` | `a$(3,3)=str$(20)`

|===

====
TIP: Integer arrays can store values from `-32768` to `32767`.
====

---

### `&,60,0` Put String

Copies a specified string variable of a fixed length into a field in a structure.

.Syntax
`&,60,0,_length_,_struct(record,field)_,_string$_`

_length_: the maximum string length to put into the record.

_array()_: the array name assigned to the structure you're reading the string from.

_string$_: the string name to read the structure data into.

.Example
 &,60,0,20,u%(1,1),na$

[start=1]
. Put a string:

`**&,60,0**,20,u%(1,1),na$`

[start=2]
. of 20 bytes:

`&,60,0,**20**,u%(1,1),na$`

[start=3]
. from the `u%()` array (record 1, field 1):

`&,60,0,20,**u%(1,1)**,na$`

[start=4]
. into the string variable `na$`:

`&,60,0,20,u%(1,1),**na$**`

TODO: show putting string longer than _length_ into struct, is it truncated?

---

### `&,60,1` Get String

This copies a string from a structure into a specified string variable.

_Syntax:_

`&,60,1,_length_,_struct(field,record)_,_string$_`

The parameters _length_, _struct(field,record)_, and _string$_ are the same as `Put String` above.

_Example:_

 &,60,1,20,u%(11,2),a$

[start=1]
. Get a string

`**&,60,1**,20,u%(11,2),a$`

[start=2]
. of 20 bytes

`&,60,1,**20**,u%(11,2),a$`

[start=3]
. from array `u%` (element 11, byte 2)

`&,60,1,20,**u%(11,2)**,a$`

[start=4]
. into `a$`.

`&,60,1,20,u%(11,2),**a$**`

====
In our earlier example user data structure, to access the third user’s password, you would:

[start=1]
. get a string:

`**&,60,1**,20,u%(11,2),a$`

[start=2]
. of 20 bytes:

`&,60,1,**20**,u%(11,2),a$`

[start=3]
. from the `u%` array (element 11, byte 2):

`&,60,1,20,**u%(11,2)**,a$`

[start=4]
. into the string variable `a$`:

`&,60,1,20,u%(11,2),**a$**`

====

---

### `&,60,2` Load structure from disk

Loads the specified structure on disk into an array.

_Syntax:_

`&,60,2,0,_struct(field,record)_,_filename$_,_device_`

_Example:_

 &,60,2,0,u%(0,0),dr$+"u.handles",dv%

NOTE: You do not have to load the file at the start of the array.

// The starting element is specified in the command.  The example loads the file `u.handles` into the `u%()` array, starting at the beginning of the array.

`**&,60,2,0,**u%(0,0),dr$+"u.handles",dv%`

[start=1]
. Load a structure:

`**&,60,2,0**,u%(0,0),dr$+"u.handles",dv%`

NOTE: The `0` is believed to be a necessary but ignored parameter.

[start=2]
. Use the `u%()` array (element 0, byte 0):

`&,60,2,0,**u%(0,0)**,dr$+"u.handles",dv%`

[start=3]
. Use the drive prefix `dr$`, plus the fictitious `"u.handles"` filename:

`&,60,2,0,u%(0,0),**dr$+"u.handles"**,dv%`

[start=4]
. `dv%` is the device number to load the structure from:

`&,60,2,0,u%(0,0),dr$+"u.handles",**dv%**`

---

### `&,60,3` Save a structure to disk

This saves a structure to a specified disk file.

_Parameters:_

`&,60,3,0,_struct%(record,field)_,_bytes_,_filename$_,_device_`

The parameters _struct%(record,field)_, _bytes_, and _filename$_ are the same as in previous commands.

_device_ should be gotten with (since `u.` files live on Image drive 6):

 dr=6:gosub 3

to get the drive prefix, `dr$`, and device, `dv%`.

_Example:_

 &,60,3,0,u%(0,0),3*38,dr$+"u.handles",dv%

The starting record and field numbers to save are specified by the numbers in the array notation.
The number of bytes should be calculated by:

****
bytes per record &times; number of records (38 bytes &times; 3 records in the example).

// :icon: fa-hand-point-right

Don't forget: records start at `0`!
****

The starting field and record is specified with (as above) `u%(0,0)`.

[start=1]
. Save a structure:

`**&,60,3,0**,u%(0,0),3*38,dr$+"u.handles",dv%`

[start=2]
. The starting element is specified with _array()_:

`&,60,3,0,**u%(0,0)**,3*38,dr$+"u.handles",dv%`

[start=3]
. _bytes_: the number of bytes per structure, multiplied by the number of structures (3 structures &times; 38 bytes in the example):

`&,60,3,0,u%(0,0),**3*38**,dr$+"u.handles",dv%`

[start=4]
. drive prefix `dr$` + filename (the theoretical `u.handles`):

`&,60,3,0,u%(0,0),3*38,**dr$+"u.handles"**,dv%`

---

### `&,60,4` Put Date

Put an 11-digit date into a structure (stored in Binary Coded Decimal).

.Syntax
`&,60,4,0,_array(a,b)_,_string$_`

_array(a,b)_: array name(`a`=starting structure, `b`=starting byte)

_string$_: the 11-digit date string

.Example
 an$="10412208234":&,60,4,0,u%(3,0),an$

====

.Details: Binary Coded Decimal

Structs store an 11-digit date in 3 elements (6 bytes) using Binary Coded Decimal (BCD) format.
Two decimal digits are stored per byte, using the high and low _nybbles_ (_i.e._, 4-bit halves of an 8-bit number).

[code, basic]
an$="10412208234":&,60,4,0,u%(0,1),an$

[cols="8"]
[%autowidth]
|===
// 4 cells, cols 2-3, 4-5, 6-7 span
>|Element
2+^|`u%(0,1)`
2+^|`u%(0,2)`
2+^|`u%(0,3)`
>|_unused_

// 8 cells
>| Binary
^| `%0001&nbsp;%0000`
^| `%0100&nbsp;%0001`
^| `%0010&nbsp;%0010`
^| `%0000&nbsp;%1000`
^| `%0010&nbsp;%0011`
>| `%0100`
>| `%xxxx`

>| Decimal
>| `1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0`
>| `4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1`
>| `2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2`
>| `0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8`
>| `2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3`
>|  `&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4`
>|  `&nbsp;&nbsp;&nbsp;&nbsp;x`
|===

====

---

### `&,60,5` Get Date

Get an 11-digit date from structure.
The date is stored in Binary Coded Decimal (BCD) format as shown above.

_Parameters:_

`&,60,5,0,_array(a,b)_,_string$_`

`array(_rec_,_field_)`: array name(_record_,_field_)

_string$_: string name

.Example
 &,60,5,0,u%(0,1),an$:&,15:&an$

. `&,60,5,0,u%(0,1),an$`: Get a date from the struct into `an$`.

. `&,15`: convert `an$` into a long date string.

. `&an$`: display the long date string.

---

### `&,60,6` Scan Structures

Scan through a field in a structure, testing whether various conditions are true on variables.
If the condition is true, perform an operation on another field in the structure.

_Syntax:_

`&,60,6,_num_,_command_,_a%(a,b)_,_b%(a,b)_,_size_,_bits_,_test_`

.i.GF
 a%=0:if s%(0,0) then:&,60,6,s%(0,0),0,s%(0,1),s%(1,1),80,1,2^ac%

.i.MM.load
 &,60,6,x1%(0,0),0,x1%(0,1),x1%(1,1),36,4096,2^ac%

 &,60,6,x1%(0,0),5,x1%(0,1),x1%(0,1),36,8192,f

 &,60,6,x1%(0,0),7,x1%(0,1),x1%(0,1),36,16384,id

////

The syntax has changed between the comments in the source code and i.UD line 3950
updated:
&,60,6,num,bits,a(a,b),b(a,b),size,com,test

Example:
&,60,6,rn,$80,ud%(0,1),ud%(0,1),60,2,2:c%=a%

ud%(0,1),ud%(0,1) -> reads and puts it back?
////

`num`: # of fields in the struct to scan

`bits`: the bits to set if _test_ is true

`flag%(_record_,_field_)`: the field on which to set `bits` if `test` is true.

====
NOTE: _record_ may be a dummy parameter, more tests needed.
====

// `b(a,b)`: starting object(_element_,_byte_)
`scan%(_rec_,_field_)`: field to scan

`size`: record size in bytes

`command`: command number:

.Scan Struct Commands
[%autowidth]
|===
| 0| 2 byte and, <>0
| 1| 2 byte and, ==0
| 2| 2 byte cmp, <
| 3| 2 byte cmp, >=
| 4| date cmp, <
| 5| date cmp, >=
|===

_test_: the object to test for
(apparently can be either a variable or a number, maybe the byte number?)

.Example: `i.UD` from Image 2.0
The following code scans the U/D directory for entries which have an upload date older than `ld$`, (setting `$4f` on `ud%(0,1)` if the entry matches):

 3950 &,60,6,rn,$4f,ud%(0,1),ud%(3,1),60,4,ld$:b%=a%

//    &,60,6,rn,$80,ud%(0,1),ud%(0,1),60,2,2:c%=a%

`&,60,6`: scan struct

`rn`: record number, how many structures to scan in the directory

`$4f`: `%01001111` in binary, #FIXME# still researching the purpose of this

`ud%(0,1)`: #FIXME#

`ud%(3,1)`: Upload date

`60`: record size, in bytes

`4`: date comparison, `<` (less than)

`ld$`: last call date (the comparison object).
Can apparently be a string name, or number of an array?

_Returns:_

`a%`: count of fields the comparison returns as matching `test`.

`b%(a,b)`: the array containing the comparisons matching `test`.

---

### `&,60,7` Sort Structure

Sort a string array (only multi-dimensional?).
Does not work with numeric values.

_Syntax:_

`&,60,7,0,_a$(a,b)_,_start?_`

_Example:_

.i/lo/tt maint:
`&,60,7,0,a$(p+1,i),n-p`

---

### `&,60,8` Scan Numbers

Scan through a specified field in a structure for non-zero values.
`a%` holds how many non-zero values there are.
The list of non-zero values is put in a specified array.

_Parameters:_

`&,60,8,_number_,_size_,_access_,_struct%(record,field)_,_result%(1)_,_start_`

`number`: number of records to scan

`size`: size of the record, in bytes

`access`: access level to filter results by (in bits?)

====

i/MM.load::
`&,60,8,x1%(0,0),36,**8192+16384**,x1%(0,1),x2%(1),1:x2%(0)=a%`

More research needed.
This value exceeds the expected access levels of 0-9 (values 1-1023).

====

`struct%(record,field)`: the field to scan

`result%(1)`: the single-dimension array to put the results in.
`1` seems to be a dummy parameter: ignored, but necessary to be interpreted as a valid array reference.

`start`: record to start scanning at

.i.UD:
 &,60,8,rn,60,a,ud%(0,1),f%(1),1:f%(0)=a%

. `&,60,8`: Scan Numbers sub-command
. `rn`: Scan through `rn` records
. `60`: the struct is 60 bytes per record
. `a`: filter by access level `a`
. `ud%(x,1)`: look in the `ud%(_x_,1)` (_x_="don't care") record
. `f%(_x_)`: putting non-zero results in the `f%()` array
. `1`: Start at record 1.

_Returns:_
`a%`: number of results returned. `0` if none.

`a%(a)`: one-dimensional array of results, from `a%(1)` to `a%(a%)`

---

### `&,60,9` Scan Sum

.Purpose

_Syntax:_

`&,60,9,_number_,_size_,_struct%(record,field)_`

`number`: number of records to scan

`size`: size of record, in bytes

`struct%(_x_,_field_)`: (record _x_="don't care"), field to scan

====
NOTE: This function call documentation seems incomplete.
====

_Example:_

None yet.

_Returns:_

`a%`: #FIXME#: total of values in record?

---

### `&,60,10` Copy Structure

Copy one record to another.

_Syntax:_

`&,60,10,_size_,_a1(a,b)_,_a2(a,b)_`

`size`: size of record

`a1(a,b)`: source record

`a2(a,b)`: destination record

_Example:_

.i/IM.logon
----
4694 if x<>fb%(.,.) then for a=x to fb%(.,.)-1:&,60,10,60,fb%(.,a+1),fb%(.,a):next <1>
----
<1> `if x<>fb%(0,0)`: if `x` does not equal the number of records in the structure [`fb%(0,0)`], then copy record `a+1` to record `a` in a loop.

---

### `&,60,11` Scan for String

Scan structure for a string present in a specified array.

_Parameters:_

`&,60,11,_num_,_size_,_op_,_str_,_a1(a,b)_,_a2(b)_,_start_`

`num`: number of records

`size`: size of record

`op`: #FIXME#: array number in table?

`str`: #FIXME#: string/string literal to scan for?

`a1(a,b)`: source record to scan

`a2(b)`: target 1-dimension array to put results into

`start`: record to start scanning from

_Example:_

None yet.

////
arrays1:
		.text "tbdenACDEFAS"
arrays2:
		.text "TBTDN"
		.byte $80, $80, $80, $80, $80
		.text "CO"

		tT
		bB
		dT
		nN
		A{$80}
		C{$80}
		D{$80}
		E{$80}
		F{$80}
		AC
		SO
////

.Arrays used by `Scan String`
[%header]
[%autowidth]
|===
| Number | Array | Purpose
|  1 | `tt$()` | editor text array
|  2 | `bb$()` |
|  3 | `dt$()` |
|  4 | `ed$()` |
|  5 | `nn$()` |
|  6 | `a%()`  |
|  7 | `c%()`  |
|  8 | `d%()`  |
|  9 | `e%()`  |
| 10 | `f%()`  |
| 11 | `ac%()` | access info
| 12 | `so%()` | subops
|===

---

### `&,60,12` Game Scan

.Purpose

_Parameters:_

`&,60,12,_count_,_size_,_a$_,_a%(a,b)_,_b$_`

`count`:

`size`: size of the record to scan

`a$`:

`a%(a,b)`:

`b$`:

_Example:_

None yet.

---

### `&,60,13` Text Read

_Purpose:_

Not sure yet.

_Syntax:_
`&,60,13,number,reclen,scan(),bits,text(),strlen`
