== POKEs and Memory Locations [[pokes]]

``poke``s control various flags maintained by the Image BBS machine language (ML).

[%autowidth]
[%header]
|===
| Decimal | BASIC Variable | Hex | ML Label | Purpose
| `830`
|
| `$33e`
|
| Time limit

| `951`
| `ll%`
| `$3b7`
| `modclmn`
| Terminal width in columns.

| `970`
| _n/a_
| `$3ca`
| `usrlin`
| Number of lines output.
If the **More Prompt** is enabled, compare `usrlin` to `usrlinm` to know when to display the prompt.

Line output count can be reset with `poke 970,0`.

| `971`
| `mp%`
| `$3cb`
| `usrlinm`
| Terminal height in rows.
       
| `1010`
| _n/a_
| `$3f2`
| `timeset`
| Time set flag.
`0`=Clock has been set, stop flashing bottom status line.

| `17138`
| _n/a_
| `$42f2`
| _n/a_
| Password mask character.

| `53252`
| _n/a_
| `$d004`
| `llen`
| Control input line length.
|===

====
TIP: ``poke``s could go away in the future, in favor of an interface table.
This replaces using a memory location with a number in the interface table.

Instead of using `poke 53252,22`, the call would be similar to `&,21,0,22`.

// https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/

Refer to the xref:prg-ampersand-calls.adoc#amp-20-read-from-interface-table[`&,20`: Read from Interface Table] or xref:prg-ampersand-calls.adoc#amp-21-write-to-interface-table[`&,21`: Write to Interface Table] commands for more information.
====
