// label used for inter-document cross-reference
### Programming Etiquette[[programming-etiquette]]

Be nice.
Write clean code.

#### Creating New Arrays

If you define any new arrays in a module, be sure not to consume unnecessary memory after you end the module.
You can do this by using the `&,27` (variable pointer save) and `&,28` (variable pointer restore) calls.

====
Image 1.2 had just one level of variable pointer save and restore.
Image 1.3 and above adds multiple levels of save and restore with an additional parameter.
====

[source]
----
3000 &,27,2 <1>
3002 dim u%(10,20) <2>
...
3010 &,28,2:goto 300 <3>
----
<1> save current variable pointers, and create variable pointer level 2

<2> create new array

<3> restore level 2 array pointers (this frees up memory used by the array but preserves variables still needed by level 1), and go to main prompt

TIP: The main prompt restores level 1 array pointers and already does a `&,28,1` there.
If you substitute `&,27,1` for `&,27,2` and `&,28,1` for `&,28,2` in the above code, line 300 will redo `&,28,1`.
This causes a `?redim'd array  error' on 306` (redimensioned array error).

### Conversion and Backward Compatibility

Image v3.0 is a major change in design and programming style from previous versions.
The first reaction might be to assume that you can no longer use legacy modules created under Image v1.2a and below.
However, nearly everything written under previous versions of Image can be made to run under v3.0.
The easiest method for this is to run under "`1.3 emulation.`"
This mode greatly reduces available memory, but allows a program to make the same calls to `im` that were available under Image 1.2a.
The best method for using legacy modules is to convert them to v3.0 compliant modules.

This section is provided to help you as you attempt to convert such modules.
The v1.2a <--> v2.0 cross-reference will be your best tool, but please take time to read the notes regarding making the modules truly Image v3.0 compliant rather than just "`compatible.`"
You will want to take careful note of the theory and structure of a v3.0 compliant program, found in the <<programming-etiquette,Programming Etiquette>> section of this guide.
