:toc: left
:icons: font
:experimental:

// https://github.com/Pinacolada64/ImageBBS/blob/534f39f7cbe3f8c896725bc1db94fa23416ecacf/v2/docs/%26%20commands.txt

== Structures [[structures]]

////
[source, basic]
10 rem hello **is this bold?** it is not
////

====
NOTE: 2024-06-27: Documentation is under heavy development, correction and discovery.
Feedback welcome.
====

_Structures_ (or _structs_ for short) allow you to access and manipulate the memory used by arrays at machine language speeds.

One benefit is that performing a struct search operation takes less RAM, and is much faster than searching through an array in BASIC with a `for...next` loop.

// TODO: EXAMPLE CODE

Programmed properly, structs save RAM compared to having multiple string and numeric arrays defined to, say, hold information about a U/D library:

* filename and filetype
* the block size
* times downloaded
* upload date and last download date
* uploader`'s handle
* which computer it`'s for

You can now hold all this information within a _single_ struct array, performing:

* searches
* sorts
* filtering the list of files based on a substring match
* and more.

You can store multiple types of data in a single struct record.
Each piece of information is stored in one or more "`columns`" called a _field_.
Multiple fields make up a _record_.
You can perform operations on the data in the fields and records using `&,60` or `&,68`, and various sub-commands.

=== Static Arrays

The arrays are considered _static_ because, like static strings embedded in BASIC text (such as `a$="hello"`), the size of individual fields can`'t change once the struct is defined.
// (unless the string is concatenated to or redefined entirely).

====
NOTE: Currently, there is no option to resize a struct without first copying records to another struct which is the desired record size.
See <<copy-record>>.
====

There are functions to:

* put a string into a struct record, and get a string from a struct record
* put an Image BBS-encoded 11-digit date into a struct record, and conversely read it back
* sort and filter data
* test and collect information from the struct, then put the results in another array
* copy a record from one struct to another record in the same or a different struct
* read a text file into a struct
* load and save structs

// FIXME: more functions

_Elements_ are the individual "`boxes`" in the array that data is held in.

Strings can be stored in either a floating point array [like `a()` or `b()`], or an integer array [like `a%()` or `b%()`].

* Two bytes of a string`'s text can be stored per element of an integer array

* Five bytes of a floating point array, or 4 bytes... #FIXME#

.Representation of a Sample Two-Dimensional Integer Array
[%autowidth]
[%header]
[col="h1,2,3"]
|===
| 3+^| Record (0,_x_)
| **Field (_0_,0)** | `x%(0,0)` | `x%(0,1)` | `x%(0,2)`
| **Field (_1_,0)** | `x%(1,0)` | `x%(1,1)` | `x%(1,2)`
| **Field (_2_,0)** | `x%(2,0)` | `x%(2,1)` | `x%(2,2)`
|===

////
TODO: later
Let`'s write a BASIC program to fill and display the elements of an integer array, and then we`'ll show how to refer to the elements:

.Sample Array
#TODO#: x%(field,record)
```
10 print
20 end
```
////

It is suggested that you use numeric instead of string arrays, since this will allow you to both access the elements as numeric data, as well as put and get strings.

// TODO: can you use string arrays?

Floating point arrays use 5 bytes per element.
Integer arrays use 2 bytes per element.
When deciding to use structs, you should determine what types of data you will need to store, and how much memory that data will require.

.User Data, Part 1
====
As a running example, let`'s design a struct to hold a user’s ID#, handle, and password.
A module will be written to store, edit, and retrieve data to/from this struct.

* The ID is an integer type (never > 32767), requiring 2 bytes.
* The handle can be up to 20 characters.
* The password can be up to 15 characters.

Since the integers store in 2 bytes, the total number of bytes needed is 37 (2 + 20 + 15).
Thirty-seven bytes would require either:

// &times; == &#215
* 19 integer elements (2 bytes per element &#215; 19 elements = 38 bytes)

_or_

* 8 floating point elements (5 bytes per element &#215; 8 elements = 40 bytes).

Now that you have the basic concept of the struct, let’s look in a little more detail.
Here is a byte-by-byte map of the struct we designed.

[%header]
[%autowidth]
.Sample "`User Data`" Struct Layout
|===
| Element Position | Byte Position | Data | Type | Bytes Used
| Element 0 | Bytes 00-01 | ID# | Integer | 2 bytes
| Element 1 | Bytes 02-21 | Handle | String | 20 bytes
| Element 11 | Bytes 22-36 | Password | String | 15 bytes
| Element 18½ | Byte 37 | _unused_ | _n/a_ | 1 byte
|===

// Representation of user data struct

."`User Data`" Struct Data Storage [[user-data-storage]]
[cols="12"]
[%autowidth]
|===
// 6 cells, cols 2-3, 4-5, 6-7, 8-9, 10-11 span
>|Element
^| `u%(0,0)`
^| `u%(0,1)`
^| `u%(0,2)`
^| `u%(0,3)`
^| `u%(0,4)`
^| `u%(0,5)`
^| `u%(0,6)`
^| `u%(0,7)`
^| `u%(0,8)`
^| `u%(0,9)`
^| `u%(0,10)`

>| Byte&#160;Pos
^| `00&#160;01`
^| `02&#160;03`
^| `04&#160;05`
^| `06&#160;07`
^| `08&#160;09`
^| `10&#160;11`
^| `12&#160;13`
^| `14&#160;15`
^| `16&#160;17`
^| `18&#160;19`
^| `20&#160;21`

>| Data
^| ID#
10+^| Handle _(20 bytes)_

>| Bytes
^| `0 1`
^| `P I`
^| `N A`
^| `C O`
^| `L A`
^| `D A`
^| _x x_
^| _x x_
^| _x x_
^| _x x_
^| _x x_
|===


[cols="10"]
[%autowidth]
|===
// 10 cells, cols 9-10 span
>|Element
^| `u%(0,11)`
^| `u%(0,12)`
^| `u%(0,13)`
^| `u%(0,14)`
^| `u%(0,15)`
^| `u%(0,16)`
^| `u%(0,17)`
2+^| `u%(0,18)`

>| Byte&#160;Pos
^| `22&#160;23`
^| `24&#160;25`
^| `26&#160;27`
^| `28&#160;29`
^| `30&#160;31`
^| `32&#160;33`
^| `34&#160;35`
^| `36`
^| `37`

>| Data
8+^| Password _(15 bytes)_
^| _unused_

>| Bytes
^| `P A`
^| `S S`
^| `W O`
^| `R D`
^| _x x_
^| _x x_
^| _x x_
^| _x_
^| _unused_
|===

TIP: Because the unused byte 37 is _not_ on an even element boundary (the previous element is an odd number of bytes), it cannot be used.

Since the ID# is an integer anyway, it would be best to use an integer array.
The definition would look like this:

[source,basic]
dim u%(18)

TIP: Remember that arrays start at element 0!
There are 19 bytes in this struct, 0-18.

Of course, you may want to store more than one of these records in memory.
To do so, you would need a 2-dimensional array.
(Suppose that _x_ is the number of records you want.)
This would change the `dim` statement to:

[source,basic]
dim u%(18,x-1)

====

=== Some New Terminology

// Ryan added this next bit, and changed previous PRG 3.0 terminology, e.g., s%(2,n) ("element,byte") to "field,record"

To refer to data in a struct, and hopefully reduce confusion about "`elements`" and "`bytes,`" the following terminology will be used:

* The first number in the array notation is the _field number_ (like a field within a record of a RELative file).
It`'s recommended that the field number be an even number, since integers occupy at least two bytes.

* The second number is the _record number_.
When the size of the struct is ``dim``ensioned, you use this value to address individual records within the struct.

====
NOTE: _Record_ and _field_ are specified in what most people and programs would consider reverse order (in a database, a record is composed of fields of information).
Sorry, there`'s no way around this (that we`'re aware of).
====

.Fields in Records
[width="100%",options="header",cols="6"]
|====
^| `u%(_field,record_)` 2+^| Fields 0-1 ^| Field 2 ^| Field 3 ^| Field 4
| Record 0 [`u%(0,0)`] 5+^| -- _configuration information_ --
// | Record 1 2+^| a \| b ^| c ^| d ^| e
| Record 1 ^| a ^| b ^| c ^| d ^| e
| Record 2 2+^| f \| g ^| h ^| i ^| j
| Record 3 2+^| k \| l ^| m ^| n ^| o
|====

====
TIP: Record `0`, field `0` [_e.g._, `u%(0,0)`] is often used to hold the number of records in the struct.
Record `0` may hold additional information in other fields during the lifetime of the struct.
====

=== Using Structs

Now down to the important part: how to use all of this!
The struct system is called with either `&,60,_sub-function_,...` or `&,68,_sub-function_,...`.

There are currently 14 sub-functions supported by the struct routines.
They are documented below.

=== Numeric Values and Structs

The array used with structs is either an integer or floating point type.
To put numeric values into--or get numeric values from--a struct requires no special struct calls.

// Is this supported?
// If you are using string arrays,
You may use code similar to the following examples:

.Get Number From and Put Number Into Struct
[%header]
[%autowidth]
|===
| Get value | Put value
| `f=a%(3,3)` | `a%(3,3)=20`

//| `f` | `a$(3,3)=str$(20)`

|===

====
TIP: Integer arrays can store values from `-32768` to `32767`.
====

'''

=== `&,60,0` Put String [[put-string]]

Copies a specified string variable (up to a specified length) into a field of a record of a struct.

.Syntax
`&,60,0,` _length_, _struct%(field, record)_, _string$_

.Parameters

_length_: the maximum string length to put into the record.

_struct%(field, record)_: the struct name, field and record you`'re putting the string into.

_string$_: the string variable name to assign the struct data to.

.Put String Into Struct
[source,basic]
&,60,0,20,u%(1,1),na$

[start=1]
. Put a string:

`**&,60,0**,20,u%(1,1),na$`

[start=2]
. of up to 20 bytes:

`&,60,0,**20**,u%(1,1),na$`

[start=3]
. from the `u%()` array (field 1, record 1):

`&,60,0,20,**u%(1,1)**,na$`

[start=4]
. into the string variable `na$`:

`&,60,0,20,u%(1,1),**na$**`

#TODO#: test if putting string longer than _length_ into struct is truncated--it should be.

.Returns

`?type mismatch&#160;&#160;error`: if the parameter _string$_ is not a string variable #FIXME#

'''

=== `&,60,1` Get String

This copies data from a field in a struct into a specified string variable.

.Syntax

``&,60,1,``_length_, _struct%(field, record)_, _string$_

.Parameters

The parameters _length_, _struct%(field, record)_, and _string$_ are the same as those used by <<put-string>>.

.Get String From Struct
[source,basic]
&,60,1,20,u%(11,2),a$

.User Data, Part 2
====
In our earlier example user data struct, to access the third user’s password, you would do this:

[source]
&,60,1,20,u%(11,3),a$

TIP: Remember, the first record starts at `0`, but generally this holds configuration information.

[%autowidth]
[%header]
|===
| Parameter | Purpose
| `&,60,1,`...
| Get a string...

| `20,`...
| ...of at most 20 bytes...

| `u%(11,3),`...
| ...from the array `u%()`, record `3`, field `11`...

| `a$`
| ...into the string variable `a$`.
|===

====

'''

=== `&,60,2` Load Struct from Disk [[load-struct]]

Loads the specified struct on disk into an array.

.Syntax

``&,60,2,0,`` _struct%(field, record)_, _filename$_, _device_

.Parameters

``&,60,2,0,``: Required parameters to perform the call.

_struct%(field, record)_,: The struct name `struct%()` to hold the ``load``ed data, plus the `record` and `field` to start ``load``ing to.

_filename$_,: the filename (either a string literal or string variable) to ``load``.

_device_: the device number to ``load`` the struct data from.

.Setup
Assign the variable `dr` to the Image drive number desired, and `gosub 3`.
This returns _device_ (`dv%`).
This also returns the drive prefix, `dr$`.

====
TIP: For our example, we`'ll set `dr=6`, since `u.` files are stored on Image drive 6.
====

[source,basic]
dr=6:gosub 3

.Load Struct from Disk
[source,basic]
&,60,2,0,u%(0,0),dr$+"u.handles",dv%

.&,60,2 Parameters

[start=1]
. Load a struct:

`**&,60,2,0**,u%(0,0),dr$+"u.handles",dv%`

====
NOTE: The `0` is believed to be a necessary but ignored parameter.
====

[start=2]
. Use the `u%()` array (load to record `0`, field `0`):

[source]
&,60,2,0,u%(0,0),dr$+"u.handles",dv%

====
NOTE: You do not have to load the file at the start of the array.
The starting record and field are specified in the array notation: `struct%(_field_,_record_)`.
This example loads the file `u.handles` into the `u%()` array, starting at the beginning of the array `(0,0)`.
It could load starting at `(0,5)`--record `5`, field `0`--or anywhere else you want, as long as it is within the bounds of the struct`'s ``dim``ensions.
====

[start=3]
. Use the drive prefix `dr$`, plus the fictitious `"u.handles"` filename:

[source]
&,60,2,0,u%(0,0),dr$+"u.handles",dv%

[start=4]
. `dv%` is the device number to load the struct from:

`&,60,2,0,u%(0,0),dr$+"u.handles",**dv%**`

'''

=== `&,60,3` Save a Struct to Disk

This saves a struct to a specified disk file.

.Syntax

``&,60,3,0,`` _struct%(field, record)_, _bytes_, _filename$_, _device_

.Setup
// TODO: use `include::` from `&,60,2` setup

.Parameters

``&,60,3,0,`` _struct%(field, record)_, _bytes_, _filename$_, _device_

The parameters _struct%(field, record)_, _bytes_, _filename$_, and _device_ and their usage are the same as in <<load-struct>>.

The starting record and field numbers to save are specified by the numbers in the array notation.

.Save Struct to Disk
[source,basic]
&,60,3,0,u%(0,0),3*38,dr$+"u.handles",dv%

.Calculating the Size of the Struct to Save
****
The number of bytes should be calculated using the formula:

_bytes per record_ &#215; _number of records_

Integer arrays take 2 bytes per record.
Floating-point arrays take 5 bytes per record.

(There are 38 bytes per record &#215; 3 records in the example.)

NOTE: Don`'t forget: records start at `0`, which is struct configuration information.
****

The starting record and field is specified with (as above) `u%(0,0)`.

[start=1]
. Save a struct:

`**&,60,3,0,**u%(0,0),3*38,dr$+"u.handles",dv%`

[start=2]
. The starting record and field numbers are specified with _struct%(field, record)_:

`&,60,3,0,**u%(0,0),**3*38,dr$+"u.handles",dv%`

[start=3]
. _bytes_: the number of bytes the struct occupies is the number of records multiplied by the bytes per record.
In our example, 3 records &#215; 38 bytes, using an integer array:

`&,60,3,0,u%(0,0),**3*38,**dr$+"u.handles",dv%`

[start=4]
. drive prefix `dr$` + filename (the theoretical `u.handles`):

`&,60,3,0,u%(0,0),3*38,**dr$+"u.handles",**dv%`

[start=5]
. device `dv%`, set by `gosub 3` before the struct save call

'''

=== `&,60,4` Put Date [[put-date]]

Put an 11-digit date string into a struct (which is stored in 6 bytes as Binary Coded Decimal).

.Syntax
`&,60,4,0,` _struct%(field, record)_, _string$_

_struct%(field, record)_: struct name, record and field to store date in

.Parameters

_string$_: the 11-digit date string (either a literal string or string variable?) #FIXME#

.Returns
`?illegal quantity&#160;&#160;error` if the date string is not 11 digits

.Put Date Into Struct
[source,basic]
an$="20412208234":&,60,4,0,u%(3,0),an$

#TODO#: Explain example.

.Details: How Put Date Stores a Date
****
Put Date stores an 11-digit date in 3 integer elements (6 bytes).
The first 5 bytes use Binary Coded Decimal (BCD): each byte holds two decimal digits (`0`-`9`), one in each _nybble_ (4-bit half of the byte).
The 6th byte is the weekday digit, as a character.

The digits are not stored in the order they appear in the string: the weekday goes last, so the year comes first.
That way, comparing the bytes in order compares the dates in time order, which is how <<scan-struct,`&,60,6`>> tests whether one date is before another.

[source,basic]
an$="20412208234":&,60,4,0,u%(1,0),an$

[%autowidth]
[%header]
|===
| Byte | Element | Holds | Digits from `an$` | Stored as

| 1
| `u%(1,0)`
| year
| 2-3: `04`
| `$04` (`%0000&#160;%0100`)

| 2
| `u%(1,0)`
| month
| 4-5: `12`
| `$12` (`%0001&#160;%0010`)

| 3
| `u%(2,0)`
| date
| 6-7: `20`
| `$20` (`%0010&#160;%0000`)

| 4
| `u%(2,0)`
| hour
| 8-9: `82`
| `$82` (`%1000&#160;%0010`)

| 5
| `u%(3,0)`
| minute
| 10-11: `34`
| `$34` (`%0011&#160;%0100`)

| 6
| `u%(3,0)`
| weekday
| 1: `2`
| `$32`, the character `2`
|===

An hour of `12` is stored as `00`, and `92` as `80`, so that 12 o`'clock sorts before 1 o`'clock (see xref:prg-ampersand-calls.adoc#newdate[`&,15,5`]).
<<get-date,`&,60,5`>> changes them back.
****

'''

=== `&,60,5` Get Date [[get-date]]

Convert a 6-byte Binary Coded Decimal (BCD) date string (as shown above) to the Image BBS 11-digit date format.

.&,60,5 Parameters

`&,60,5,0,` _struct%(field, record)_, _string$_

[%header]
[%autowidth]
|===
| Parameter | Purpose
| `&,60,5,0`,...
| Get date call. `0` seems to be an ignored but necessary parameter.

| `struct%(_field, record_)`,...
| struct name, field, record...

| _string$_
| ...string variable to hold the converted 11-digit date and time.
|===

.Get Date From Struct
[source,basic]
&,60,5,0,u%(0,1),an$:&,15:&an$

[%header]
[%autowidth]
|===
| Parameter | Purpose
| `&,60,5,0,`
| Get a date string...

| `u%(0,1),`
| ...from the struct `u%()`, record `1`, field `0`...

| `an$:`
| ...into the string `an$`.

| `&,15`
| Convert `an$` into a long date string.

| `&an$`
| Display the long date string.
|===

.Result
#TODO#: finish the output

'''

=== `&,60,6` Scan Struct [[scan-struct]]

Test a field in each record of a struct, and set bits in the record's flags word where the test is true.
`a%` returns the number of records where the test was true.

====
NOTE: This description comes from reading the source code (see <<scan-struct-source>>).
The Image BBS calls in <<scan-struct-examples>> all fit it, but it has not been tested on a running BBS yet.
====

.Syntax
`&,60,6,` _count_, _oper_, _flags%(field, record)_, _object%(field, record)_, _size_, _bits_, _test_

.Parameters
[%autowidth]
[%header]
|===
| Parameter | Range | Purpose

| _count_
| `0`-`255`
| Number of records to scan

| _oper_
| `0`-`255`
| The test to do: see <<scan-struct-oper>>

| _flags%(field, record)_
|
| The flags word of the first record to scan.
The result bits are set here.

| _object%(field, record)_
|
| The field to test in the first record to scan

| _size_
| `0`-`255`
| Record size in bytes.
After each record, both _flags_ and _object_ move on by this many bytes.

| _bits_
| `0`-`65535`
| The bits to set in the flags word when the test is true

| _test_
| `0`-`65535`, or a date string
| What to compare _object_ with: a number, or an 11-digit date string if _oper_ includes `64`
|===

.Returns
`a%`: the number of records where the test was true.

==== The Operation Byte [[scan-struct-oper]]

_oper_ is made of bit fields:

[%autowidth]
[%header]
|===
| Bit | Value | Meaning

| 0
| `1`
| Invert the result

| 1-2
| `0` or `6`
| How each byte is compared: `0` = `and` (_object_ `and` _test_); `6` = compare.
(`4` = `and`, then compare with _test_: true if not all of _test_'s bits are set.)

| 3
| `8`
| With compare: the result is "`less than`".
Without it: "`not equal`", or a non-zero `and`.

| 6
| `64`
| Date mode: compare a 6-byte date (stored by <<put-date,`&,60,4`>>) instead of a 2-byte integer

| 7
| `128`
| Keep bits already set: don't clear _bits_ before testing
|===

.Useful _oper_ Values
[%autowidth]
[%header]
|===
| _oper_ | True when | Used in

| `0`
| _object_ `and` _test_ is not `0`
| `i.GF`, `i/MM.load`, `i.UD`

| `1`
| _object_ `and` _test_ is `0`
|

| `5`
| _object_ has all of _test_'s bits set
| `i/MM.load`

| `6` / `7`
| _object_ is not equal to / equal to _test_
| `i/MM.load` (`7`)

| `14` / `15`
| _object_ is less than / greater than or equal to _test_ (unsigned)
|

| `78` (`$4e`) / `79` (`$4f`)
| The date is before / the same as or after _test_
| `i.UD`
|===

Add `128` to any of these to keep the bits already set (`$80` is `128` on its own: `0` plus "`keep`").

[NOTE]
====
The source code comment lists "`commands`" `0`-`5` (`and <>0`, `and =0`, `cmp <`, `cmp >=`, date `<`, date `>=`).
That is the order of the list, not the values to pass: Image BBS passes `$4e` and `$4f` for the two date tests, for example.
====

==== What Happens for Each Record

. Unless _oper_ includes `128`, the bits in _bits_ are cleared in the record's flags word.
. _object_ is compared with _test_ byte by byte, starting with the first byte.
For an integer, that is the high byte, so integers compare as unsigned numbers: `-1` in the array is `65535`.
For a date, that is the year (see <<put-date>>), so dates compare in time order.
. If the test is true (after inverting, if _oper_ includes `1`), the bits in _bits_ are set in the flags word, and `a%` goes up by `1`.
. _flags_ and _object_ move on by _size_ bytes, to the next record.

==== Tricks

Clear a bit in every record::
Use the flags word as _object_, _oper_ `0`, and the bit as both _bits_ and _test_.
The bit is cleared before the test, so the test is never true:
+
[source,basic]
&,60,6,rn,0,ud%(0,1),ud%(0,1),60,2,2

Count the records with a bit set, without changing anything::
The same, but with _oper_ `128` (`$80`), so nothing is cleared first.
`a%` is the count:
+
[source,basic]
&,60,6,rn,$80,ud%(0,1),ud%(0,1),60,2,2:c%=a%

==== Examples [[scan-struct-examples]]

===== i.UD: New, Tagged and Unvalidated Files

From Jack Followay's `i.UD` (`Jack Followay/i.UD-structs.lbl`, line `{:3940}` on).
Each 60-byte record of `ud%()` is one file.
`ud%(0,0)` holds the number of files, `rn`, and the files are records `1`-`rn`.
The fields these calls use are:

[%autowidth]
[%header]
|===
| Field | Contents

| `ud%(0,_r_)`
| Flags: `1` unvalidated, `2` tagged, `4` new since your last call, `8` downloaded since your last call, `16` uploaded before your last call

| `ud%(3,_r_)`
| Upload date

| `ud%(6,_r_)`
| Last download date
|===

[source,basic]
&,60,6,rn,$4f,ud%(0,1),ud%(3,1),60,4,ld$:b%=a%
&,60,6,rn,$4f,ud%(0,1),ud%(6,1),60,8,ld$
&,60,6,rn,$4e,ud%(0,1),ud%(3,1),60,16,ld$
if id<>ud%(1,0)then:&,60,6,rn,0,ud%(0,1),ud%(0,1),60,2,2
&,60,6,rn,$80,ud%(0,1),ud%(0,1),60,2,2:c%=a%
&,60,6,rn,$80,ud%(0,1),ud%(0,1),60,1,1:d%=a%*q

[%autowidth]
[%header]
|===
| Line | What it does

| 1
| Set bit `4` where the upload date is the same as or after `ld$` (your last call date).
`b%`: the number of new files.

| 2
| Set bit `8` where the last download date is the same as or after `ld$`

| 3
| Set bit `16` where the upload date is before `ld$`

| 4
| If you aren't the user who tagged the files (`ud%(1,0)`), clear bit `2` (tagged) in every record

| 5
| `c%`: the number of tagged files (bit `2`)

| 6
| `d%`: the number of unvalidated files (bit `1`)
|===

The module then shows `b%`, `c%` and `d%` as "`New`", "`Tagged`" and "`Unvalidated`".

===== i.GF: Files the User Can Access

[source,basic]
3166 a%=0:if s%(0,0) then:&,60,6,s%(0,0),0,s%(0,1),s%(1,1),80,1,2^ac%
3168 rn=a%:if rn then:&,60,8,s%(0,0),80,1,s%(0,1),e%(1),1

Line 3166 sets bit `1` in every 80-byte record whose access field (`s%(1,_r_)`) includes the user's access level bit, `2^ac%`.
`a%` is the number of entries the user can access.
Line 3168 then uses <<scan-numbers,`&,60,8`>> to list the records with bit `1` set.

TIP: `2^ac%` is 2 to the power of the user's access level, not "`squared`": a level 5 user's bit is `32`.
C64 BASIC's `^` can return a value slightly below a whole number; `&,60,6` rounds it down, so `int(2^ac%+.5)` is safer.

===== i/MM.load: SIGs the User Can Use

.i/MM.load: SIG list (release 231231; `core/i_MM.load.lbl`)
[source,basic]
 4006 dr=3:gosub3:&,60,2,0,x1%(0,0),dr$+"e.Siglist",dv%:goto5
 4008 dr=3:gosub3:&,60,2,0,x3%(0,0),dr$+"e.Siglist"+str$(sg),dv%:goto5
 4100 q=.:a=12:gosub11:b=a:a=8:gosub11:ifa+bthenq=1
 4102 gosub4006:ife%<>0orx1%(0,0)=0then4146
 4104 xx=-(sy$="U/D")-2*(sy$="U/X"):f=4096+2^xx
 4106 &,60,6,x1%(0,0),0,x1%(0,1),x1%(1,1),36,4096,2^ac%
 4108 &,60,6,x1%(0,0),5,x1%(0,1),x1%(0,1),36,8192,f
 4110 &,60,6,x1%(0,0),7,x1%(0,1),x1%(0,1),36,16384,id
 4112 &,60,8,x1%(0,0),36,8192+16384,x1%(0,1),x2%(1),1:x2%(0)=a%
 4114 a$=left$(an$,2):an$=mid$(an$,3):ifa%=0then4146
 4116 ifa$=">>"ora$="<<"thenr=sg+1+2*(a$="<<"):on-(r<>0)goto4124
 4118 tz=0:gosub4004:on-(r<>0)goto4124:ifa%=1thenr=1:tz=1:goto4124
 4120 &"{f6}{wht} ##  SIG Name{f6}{f6}":fori=1tox2%(0):a%=i:x=x2%(i):&,60,1,30,x1%(3,x),b$
 4122 &"{wht}\#3\# \%a  {cyn}\$b{f6}":next:&"{wht}{f6}":p$="Which SIG?":gosub6:gosub4004
 4124 ifr<1orr>x2%(0)then4168
 4126 sg=x2%(r):r=0:so%=x1%(2,sg):&,60,1,30,x1%(3,sg),s$
 4128 sg$=s$:gosub4008:bz=0:ife%then4144

[%autowidth]
[%header]
|===
| Line | What it does

| 4104
| `f` is bit `4096`, plus `1`, `2` or `4` depending on `sy$` (`2^xx`)

| 4106
| Set bit `4096` on every 36-byte SIG record whose access field (`x1%(1,_r_)`) includes the user's access level bit

| 4108
| _oper_ `5`: set bit `8192` where the flags word has all of `f`'s bits set: the user can access the SIG, and it is the right type

| 4110
| _oper_ `7`: set bit `16384` where the flags word equals `id`

| 4112
| <<scan-numbers,`&,60,8`>> lists the SIGs with bit `8192` or `16384` set
|===

[WARNING]
====
Line 4110 is very likely a bug.
It compares each SIG's flags word (`x1%(0,_r_)`) with the user's ID number, which is only true by coincidence.
This is how the line appears in release 231231 (checked against `i/MM.load` on Disk 1), not a copying mistake.

Line 4126 shows that `x1%(2,_r_)` holds the SIG's sysop (`so%=x1%(2,sg)`).
Testing that field instead would make line 4110 mean "`also list the SIGs you are sysop of`", which fits what line 4112 collects:

[source,basic]
4110 &,60,6,x1%(0,0),7,x1%(0,1),x1%(2,1),36,16384,id

As released, a SIG's sysop who doesn't have the access level for their own SIG doesn't see it in this list.
====

==== Source References [[scan-struct-source]]

[%autowidth]
[%header]
|===
| What | Where

| `&,60,6` dispatch
| `source/struct.s`: `entry2` and `functbl` (`&,60` sub-functions `4`-`13`)

| `doscan` routine
| `source/struct.s`: `doscan:` through `doscan15:`

| How _oper_ picks the comparison
| `source/struct.s`: `scanbits`, tables `opc1`, `opc2`, `opc3`, and the self-modified instructions `checkc0`-`checkc4`

| Integer and date _test_ values
| `source/struct.s`: `getword`, `evaldate`

| Command list in the source comment
| `source/struct.s`: header comment, `doscan - scan structures`
|===

Test program: `core/tests/i.test structs.lbl`, line `{:3400}`.

'''

=== `&,60,7` Sort Struct

Sort a string array (only two-dimensional?).
Does not work with numeric arrays.

.Syntax

`&,60,7,0,` _a$(a, b)_, _start_

.Parameters

_a$(a,b)_: String array to sort

_start_: Element to start sorting at?

.i/lo/tt maint: Sort Struct
====
[source,basic]
4016 for i=1 to 8:&".":&,60,7,0,a$(p+1,i),n-p:next:p=n-10

'''

=== `&,60,8` Scan Numbers [[scan-numbers]]

Scan through a specified field in a struct for non-zero values.
`a%` returns how many non-zero values there are.
The list of non-zero values are returned in the specified array.

.Syntax

`&,60,8,` _number_, _size_, _access_, _struct%(field, record)_, _result%(1)_, _start_

.Parameters

`number`: number of records to scan

`size`: size of the record, in bytes

`access`: access level to filter results by (in bits?)

`struct%(field, record)`: the struct, record and field to scan

`result%(1)`: the single-dimension array to put the results in.
`1` seems to be a dummy parameter: ignored, but necessary to be interpreted as a valid array reference.

`start`: record to start scanning at

.i/MM.load: Scan Numbers
[source,basic]
4112 &,60,8,x1%(0,0),36,8192+16384,x1%(0,1),x2%(1),1:x2%(0)=a%

[%header]
[%autowidth]
|===
| Parameter | Purpose
| `&,60,8`
| Scan Numbers sub-command

| `x1%(0,0)`
| number of records

| `36`
| the struct is 36 bytes per record

| `8192+16384`
| filter by bits 14/15 ($2000, `%00100000 00000000` + $4000, `%01000000 00000000`)

| `x1%(0,1)`
| look in the `x1%(field=_0_, record=1)` (field _0_="`don`'t care?`")

| `x2%(1)`
| put non-zero results in the `x2%()` array

| `1`
| Start at record 1.
|===

====
NOTE: More research needed.
`8192+16384` exceeds the expected access levels of 0-9 (values 1-1023).
These are the bits which lines 4108 and 4110 set using <<scan-struct,`&,60,6`>>, just before this line: see <<scan-struct-examples>>.
====

.i.UD: Scan Numbers
[source,basic]
3310 &,60,8,rn,60,a,x1%(0,1),f%(1),1:f%(0)=a%

// FIXME: order of params changed -- this is Jack's struct UD

. `&,60,8`: Scan Numbers sub-command
. `rn`: Scan through `rn` records
. `60`: the struct is 60 bytes per record
. `a`: filter by access level `a`
. `x1%(0,1)`: look in the `x1%(field=_0_, record=1)` (field _0_="don`'t care?")
. `f%(_x_)`: put non-zero results in the `f%()` array
. `1`: Start at record 1.

.Returns
`a%`: number of results returned, `0`=none.

`a%(a)`: one-dimensional array of results, from `a%(1--a)`

'''

=== `&,60,9` Scan Sum

.Syntax

`&,60,9,` _number_, _size_, _struct%(field, record)_

`number`: number of records to scan

`size`: size of record, in bytes

`struct%(field, record)`: (field="`don`'t care`"? #FIXME#), record to scan

====
NOTE: This function call documentation is incomplete.
====

.Example

None yet.

.Returns

`a%`: #FIXME#: total of values in struct?

'''

=== `&,60,10` Copy Record [[copy-record]]

Copy one record from one struct to a record in another struct.

.Syntax

`&,60,10,` _size_, _a1(a, b)_, _a2(a, b)_

.Parameters

`size`: size of record

`a1%(a,b)`: source struct `a1%()`, record `b` and field `a`

`a2%(a,b)`: destination struct `a2%()`, record `b` and field `a`

.i/IM.logon: Copy Record
====
[source,basic]
4694 if x<>fb%(.,.) then for a=x to fb%(.,.)-1:&,60,10,60,fb%(.,a+1),fb%(.,a):next
====

[%header]
[%autowidth]
|===
| Statement | Purpose
| `if x<>fb%(0,0)`
| if `x` does not equal the number of records in the struct [`fb%(0,0)`], then...

| `for a=x to fb%(.,.)-1`
| loop from `x` (the current record) to the number of records in the struct fb%() -1...
|===

=== `&,60,11` Scan for String

[%header]
[%autowidth]
|===
| Routine | Purpose
| `&,60,10,60,fb%(.,a+1),fb%(.,a)`
| copy 60-byte record `a+1` to record `a` in a loop.
|===

.i/GF-maint: Copy Record
[source]
4414 if br<>s%(0,0) then for a=br to s%(0,0)-1:&,60,10,80,s%(0,a+1),s%(0,a):next

[%header]
[%autowidth]
|===
| Routine | Purpose
| x
| x
|===

'''

=== `&,60,11` Scan for String

Scan struct for a string present in a specified field and record.
Put results (the indices of the fields the search results are found in) in the specified array.

.Syntax

`&,60,11,` _num_, _size_, _op_, _str_, _a1%(a,b)_, _a2%(b)_, _start_

.Parameters

`num`: number of records to scan

`size`: size of record

`op`: operation:

* `0` specifies a regular compare (a string literal)

* `1` specifies a pattern to match.
Here you can use two wildcard characters (like Commodore DOS):

** kbd:[f2] (in quote mode: kbd:[I]) is equal to kbd:[?], which specifies any character in its place
** kbd:[f7] (in quote mode: kbd:[H]) is equal to kbd:[*], which specifies any characters from this point to the end of the string

====
NOTE: You may only use the wildcard ``*`` following the specified string: ``text*``, not ``*text``.
====

`str`: string variable or string literal to scan for

`a1%(a,b)`: source struct _a1%()_, record _b_, field _a_, to scan

`a2%(b)`: target 1-dimension array _a2%()_, dummy element _b_, to put results into

`start`: record to start scanning from

.Returns

`a%`: the count of results returned, `0` if none.

`a2%(b)`: the array of results; each element is a search result

.Example

None yet.

'''

=== `&,60,12` Game Scan

Unknown purpose.

.Syntax

`&,60,12,` _count_, _size_, _a$_, _a%(a,b)_, _b$_

.Parameters

`count`: how many records to scan?

`size`: size of the record to scan

`a$`: a string to search for?

`a%(a,b)`: `a%()`: struct name, `a`: field and `b`: record to scan

`b$`: ?

.Example

None yet.

'''

=== `&,60,13` Text Read

Not sure yet. Read a file into a struct?

.Syntax

`&,60,13,` _number,_ _reclen,_ _scan(),_ _bits,_ _text(),_ _strlen_

// either that, or:
// game scan
// &,60,13,count,size,a$,a%(a,b),b$

.Parameters

_number,_: count of lines to read?

_reclen,_: record length?

_scan(),_: ?

_bits,_: ?

_text(),_: ?

_strlen_: ?

.Example

None yet.
