# Image BBS 3.0 Programmer`'s Reference Guide
Jack Followay, Jr.; Ryan Sherwood <sym.rsherwood@gmail.com>; Larry Hedman <larryhedman@gmail.com>; Al DeRosa <bucko219@gmail.com>
v0.1, 2021-04-14
:experimental:
// enable kbd:[] macro
:toc: left
:icons: font

// GitHub Flavored AsciiDoc
// https://gist.github.com/eirnym/25d75fcea31478956a5e307f0f5735bf

include::prg-introduction.adoc[]

### How to Use This Guide

### How to Get Help

## Programming Image BBS 3.0

### Programming Etiquette

### `im` Subroutines

### `sub.*` Module Jump Table

include::prg-ampersand-calls.adoc[]

### Image BBS Output Routine

`&"bla","bla"` and `&"bla &pound;!x"`

====

NOTE: Outputting a string containing an MCI command or string variable does not work as expected. _i.e._:

`z$="&pound;$c &pound;#3&pound;# &pound;%c":&"&pound;$z"`

does not output the contents of `z$` (which is actually `c$`, and setting 3 leading spaces for `c%`).
Instead, do this:

`z$="&pound;$c &pound;#3&pound;# &pound;%c":&z$`

====

#### `&` By Itself

This is a quick way to output the contents of `a$`.

`a$="Hello therekbd:[f6]":&`

#### Word-Wrap

Setting the variable `lp=1` and outputting text with `&"..."` word-wraps to 40 columns on the console, and whatever the remote side`'s screen width is.

Setting `lp=0` disables word-wrap, and words do not break at margins.

include::prg-structures.adoc[]

## Variables

### Integer

### Floating Point

### String

### Arrays

## POKEs and Machine Language Routines

====

TIP: ``POKE``s could go away in favor of `&,20` (interface read) and `&,21` (interface write) commands.

====

include::prg-lightbar.adoc[]

include::prg-memory-map.adoc[]

// Ray wrote this

include::prg-file-formats.adoc[]
