:toc: left
:icons: font
:experimental:

// https://github.com/Pinacolada64/ImageBBS/blob/534f39f7cbe3f8c896725bc1db94fa23416ecacf/v2/docs/%26%20commands.txt

== Structures [[structures]]

====
NOTE: 2024-06-27: Documentation is under heavy development, correction and discovery.
Feedback welcome.
====

_Structures_ (or _structs_ for short) allow you to access and manipulate the memory used by arrays at machine language speeds.

One benefit is that performing a struct search operation takes less RAM, and is much faster than searching through an array in BASIC with a `for...next` loop.

// TODO: EXAMPLE CODE

Programmed properly, structs save RAM compared to having multiple string and numeric arrays defined to, say, hold information about a U/D library:

* filename and filetype
* the block size
* times downloaded
* upload date and last download date
* uploader`'s handle
* which computer it`'s for


You can now hold all this information within a _single_ struct array, performing:

* searches
* sorts
* filtering the list of files based on a substring match
* and more.

You can store multiple types of data in a single struct record.
Each piece of information is stored in one or more "`columns`" called a _field_.
Multiple fields make up a _record_.
You can perform operations on the data in the fields and records using `&,60` or `&,68`, and various sub-commands.

Performing a struct search operation is much faster than searching through an array in BASIC with a `for...next` loop.

=== Static Arrays

The arrays are considered _static_ because, like static strings embedded in BASIC text (such as `a$="hello"`), the size of individual fields can't change once the struct is defined.
// (unless the string is concatenated to or redefined entirely).

====
NOTE: Currently, there is no option to resize a struct without first copying records to another struct which is the desired record size.
See <<copy-record>>.
====

There are functions to:

* put a string into a struct record, and get a string from a struct record
* put an Image BBS-encoded 11-digit date into a struct record, and conversely read it back
* sort and filter data
* test and collect information from the struct, then put the results in another array
* copy a record from one struct to another record in the same or a different struct
* read a text file into a struct
* load and save structs

// FIXME: more functions

_Elements_ are the individual "`boxes`" in the array that data is held in.

Strings can be stored in either a floating point [like `a()` or `b()`], or integer  [like `a%()` or `b%()`] array.

* Two bytes of a string's text can be stored per element of an integer array

* Five bytes of a floating point array, or 4 bytes... #FIXME#

.Representation of a Sample Two-Dimensional Integer Array
[%autowidth]
[%header]
[col="h1,2,3"]
|===
| 3+^| Record (0,_x_)
| **Field (_0_,0)** | `x%(0,0)` | `x%(0,1)` | `x%(0,2)`
| **Field (_1_,0)** | `x%(1,0)` | `x%(1,1)` | `x%(1,2)`
| **Field (_2_,0)** | `x%(2,0)` | `x%(2,1)` | `x%(2,2)`
|===

////
TODO: later
Let's write a BASIC program to fill and display the elements of an integer array, and then we'll show how to refer to the elements:

.Sample Array
#TODO#: x%(field,record)
```
10 print
20 end
```
////

It is suggested that you use numeric instead of string arrays, since this will allow you to both access the elements as numeric data, as well as put and get strings.

// TODO: can you use string arrays?

Floating point arrays use 5 bytes per element.
Integer arrays use 2 bytes per element.
When deciding to use structs, you should determine what types of data you will need to store, and how much memory that data will require.

.User Data, Part 1
====
As a running example, let`'s design a struct to hold a user’s ID#, handle, and password.
A module will be written to store, edit, and retrieve data to/from this struct.

* The ID is an integer type (never > 32767), requiring 2 bytes.
* The handle can be up to 20 characters.
* The password can be up to 15 characters.

Since the integers store in 2 bytes, the total number of bytes needed is 37 (2 + 20 + 15).
Thirty-seven bytes would require either:

// &times; == &#215
* 19 integer elements (2 bytes per element &#215; 19 elements = 38 bytes)

_or_

* 8 floating point elements (5 bytes per element &#215; 8 elements = 40 bytes).

Now that you have the basic concept of the struct, let’s look in a little more detail.
Here is a byte-by-byte map of the struct we designed.

[%header]
[%autowidth]
.Sample "`User Data`" Struct Layout
|===
| Element Position | Byte Position | Data | Type | Bytes Used
| Element 0 | Bytes 00-01 | ID# | Integer | 2 bytes
| Element 1 | Bytes 02-21 | Handle | String | 20 bytes
| Element 11 | Bytes 22-36 | Password | String | 15 bytes
| Element 18½ | Byte 37 | _unused_ | _n/a_ | 1 byte
|===

// Representation of user data struct

."`User Data`" Struct Data Storage
[cols="12"]
[%autowidth]
|===
// 6 cells, cols 2-3, 4-5, 6-7, 8-9, 10-11 span
>|Element
^| `u%(0,0)`
^| `u%(0,1)`
^| `u%(0,2)`
^| `u%(0,3)`
^| `u%(0,4)`
^| `u%(0,5)`
^| `u%(0,6)`
^| `u%(0,7)`
^| `u%(0,8)`
^| `u%(0,9)`
^| `u%(0,10)`

>| Byte&#160;Pos
^| `00&#160;01`
^| `02&#160;03`
^| `04&#160;05`
^| `06&#160;07`
^| `08&#160;09`
^| `10&#160;11`
^| `12&#160;13`
^| `14&#160;15`
^| `16&#160;17`
^| `18&#160;19`
^| `20&#160;21`

>| Data
^| ID#
10+^| Handle _(20 bytes)_

>| Bytes
^| `0 1`
^| `P I`
^| `N A`
^| `C O`
^| `L A`
^| `D A`
^| _x x_
^| _x x_
^| _x x_
^| _x x_
^| _x x_
|===


[cols="10"]
[%autowidth]
|===
// 10 cells, cols 9-10 span
>|Element
^| `u%(0,11)`
^| `u%(0,12)`
^| `u%(0,13)`
^| `u%(0,14)`
^| `u%(0,15)`
^| `u%(0,16)`
^| `u%(0,17)`
2+^| `u%(0,18)`

>| Byte&#160;Pos
^| `22&#160;23`
^| `24&#160;25`
^| `26&#160;27`
^| `28&#160;29`
^| `30&#160;31`
^| `32&#160;33`
^| `34&#160;35`
^| `36`
^| `37`

>| Data
8+^| Password _(15 bytes)_
^| _unused_

>| Bytes
^| `P A`
^| `S S`
^| `W O`
^| `R D`
^| _x x_
^| _x x_
^| _x x_
^| _x_
^| _unused_
|===


TIP: Because the unused byte 37 is _not_ on an even element boundary (the previous element is an odd number of bytes), it cannot be used.

Since the ID# is an integer anyway, it would be best to use an integer array.
The definition would look like this:

[source,basic]
----
dim u%(18)
----

TIP: Remember that arrays start at element 0!
There are 19 bytes in this struct, 0-18.

Of course, you may want to store more than one of these records in memory.
To do so, you would need a 2-dimensional array.
(Suppose that _x_ is the number of records you want.)
This would change the `dim` statement to:

[source,basic]
----
dim u%(18,x-1)
----

====

=== Some New Terminology

// Ryan added this next bit, and changed previous PRG 3.0 terminology, e.g., s%(2,n) ("element,byte") to "field,record"

To refer to data in a struct, and hopefully reduce confusion about "`elements`" and "`bytes,`" the following terminology will be used:

* The first number in the array notation is the _field number_ (like a field within a record of a RELative file).
It's recommended to be an even number since integers occupy at least two bytes.
* The second number is the _record number_.
When the size of the struct is ``dim``ensioned, you use this value to address individual records within the struct.

====
NOTE: _Record_ and _field_ are specified in what most people and programs would consider reverse order (in a database, a record is composed of fields of information).
Sorry, there`'s no way around this (that we`'re aware of).
====

#TODO#: a visualization of fields in a record.

.Fields in Records
[width="100%",options="header",cols="6"]
|====================
^| `u%(_field,record_)` 2+^| Fields 0-1 ^| Field 2 ^| Field 3 ^| Field 4
| Record 0 [`u%(0,0)`] 5+^| -- _configuration information_ --
// | Record 1 2+^| a \| b ^| c ^| d ^| e
| Record 1 ^| a ^| b ^| c ^| d ^| e
| Record 2 2+^| f \| g ^| h ^| i ^| j
| Record 3 2+^| k \| l ^| m ^| n ^| o
|====================

====
TIP: Record `0`, field `0` [_e.g._, `u%(0,0)`] is often used to hold the number of records in the struct.
Record `0` may hold additional information in other fields during the lifetime of the struct.
====

=== Using Structs

Now down to the important part: how to use all of this!
The struct system is called with either `&,60,_sub-function_,...` or `&,68,_sub-function_,...`.

There are currently 14 sub-functions supported by the struct routines.
They are documented below.

=== Numeric Values and Structs

The array used with structs is either an integer or floating point type.
To put numeric values into--or get numeric values from--a struct requires no special struct calls.

// Is this supported?
// If you are using string arrays,
You may use code similar to the following examples:

.Get Number From and Put Number Into Struct
[%header]
[%autowidth]
|===
| Get value | Put value
| `f=a%(3,3)` | `a%(3,3)=20`

//| `f` | `a$(3,3)=str$(20)`

|===

====
TIP: Integer arrays can store values from `-32768` to `32767`.
====

---

=== `&,60,0` Put String

Copies a specified string variable (up to a specified length) into a field of a record of a struct.

.Syntax
`&,60,0,` _length_, _struct%(field, record)_, _string$_

.Parameters

_length_: the maximum string length to put into the record.

_struct%(field, record)_: the struct name, field and record you're putting the string into.

_string$_: the string variable name to assign the struct data to.

.Put String
[source,basic]
&,60,0,20,u%(1,1),na$

[start=1]
. Put a string:

`**&,60,0**,20,u%(1,1),na$`

[start=2]
. of up to 20 bytes:

`&,60,0,**20**,u%(1,1),na$`

[start=3]
. from the `u%()` array (field 1, record 1):

`&,60,0,20,**u%(1,1)**,na$`

[start=4]
. into the string variable `na$`:

`&,60,0,20,u%(1,1),**na$**`

#TODO#: test if putting string longer than _length_ into struct is truncated -- it should be.

.Returns

`?type mismatch&#160;&#160;error`: if the parameter _string$_ is not a string variable #FIXME#

---

=== `&,60,1` Get String

This copies data from a field in a struct into a specified string variable.

.Syntax

``&,60,1,``_length_, _struct%(field, record)_, _string$_

.Parameters

The parameters _length_, _struct%(field, record)_, and _string$_ are the same as `Put String` above.

.Get String
====
[source,basic]
----
&,60,1,20,u%(11,2),a$
----
====

[IMPORTANT]
====
Feedback wanted: which is better, format 1 or format 2?
But that's just, like, your opinion, man.
====

.User Data, Part 2
====
In our earlier example user data struct, to access the third user’s password, you would do this:

 &,60,1,20,u%(11,2),a$

.Parameters

.Format 1

[%autowidth]
[%header]
|===
| Parameter | Purpose
| `&,60,1,`...
| Get a string...

| `20,`...
| ...of at most 20 bytes...

| `u%(11,3),`...
| ...from the array `u%()`, record `3`, field `11`...

| `a$`
| ...into the string variable `a$`.
|===

---

.Format 2
`**&,60,1,**20,u%(11,2),a$`

[start=1]
. Get a string...

`&,60,1,**20,**u%(11,2),a$`

[start=2]
. of at most 20 bytes...

`&,60,1,20,**u%(11,2),**a$`

[start=3]
. from the array `u%()`, record `2`, field `11`...

`&,60,1,20,u%(11,2),**a$**`

[start=4]
. into the string variable `a$`

====

---

=== `&,60,2` Load Struct from Disk

Loads the specified struct on disk into an array.

.Syntax

``&,60,2,0,`` _struct%(field, record)_, _filename$_, _device_

.Parameters

``&,60,2,0,``: Required parameters.

_struct%(field, record)_,: #FIXME#

_filename$_,: #FIXME#

_device_: #FIXME#

.Setup
Assign the variable `dr` to the Image drive number desired, and `gosub 3`.
This returns _device_ (`dv%`).

(For our example, we'll set `dr=6`, since `u.` files live on Image drive 6.)

[source,basic]
dr=6:gosub 3

This also returns the drive prefix, `dr$`.

.Load Struct from Disk
====
[source,basic]
----
&,60,2,0,u%(0,0),dr$+"u.handles",dv%
----
====

.Parameters

[start=1]
. Load a struct:

`**&,60,2,0**,u%(0,0),dr$+"u.handles",dv%`

====
NOTE: The `0` is believed to be a necessary but ignored parameter.
====

[start=2]
. Use the `u%()` array (load to record `0`, field `0`):

`&,60,2,0,**u%(0,0)**,dr$+"u.handles",dv%`

====
NOTE: You do not have to load the file at the start of the array.
The starting record and field are specified in the array notation.
This example loads the file `u.handles` into the `u%()` array, starting at the beginning of the array `(0,0)`.
It could load starting at `(0,5)` -- record `5`, field `0` -- or anywhere else you want, as long as it is within the bounds of the struct's ``dim``ensions.
====

[start=3]
. Use the drive prefix `dr$`, plus the fictitious `"u.handles"` filename:

`&,60,2,0,u%(0,0),**dr$+"u.handles"**,dv%`

[start=4]
. `dv%` is the device number to load the struct from:

`&,60,2,0,u%(0,0),dr$+"u.handles",**dv%**`

---

=== `&,60,3` Save a Struct to Disk

This saves a struct to a specified disk file.

.Syntax

``&,60,3,0,`` _struct%(field, record)_, _bytes_, _filename$_, _device_

.Setup
#TODO# use `include::` from `&,60,2` setup

.Parameters

``&,60,3,0,`` _struct%(field, record)_, _bytes_, _filename$_, _device_

The parameters _struct%(field, record)_, _bytes_, _filename$_, and _device_ and their usage are the same as in <<load-struct>>.

The starting record and field numbers to save are specified by the numbers in the array notation.

.Save Struct to Disk
[source,basic]
&,60,3,0,u%(0,0),3*38,dr$+"u.handles",dv%

.Calculating Struct Size to Save
****
The number of bytes should be calculated using the formula:

_bytes per record_ &#215; _number of records_

Integer arrays take 2 bytes per record.
Floating-point arrays take 5 bytes per record.

(There are 38 bytes per record &#215; 3 records in the example.)

NOTE: Don't forget: records start at `0`!
****

The starting record and field is specified with (as above) `u%(0,0)`.

[start=1]
. Save a struct:

`**&,60,3,0,**u%(0,0),3*38,dr$+"u.handles",dv%`

[start=2]
. The starting record and field numbers are specified with _struct%(field, record)_:

`&,60,3,0,**u%(0,0),**3*38,dr$+"u.handles",dv%`

[start=3]
. _bytes_: the number of bytes the struct occupies is the number of records multiplied by the bytes per record.
In our example, 3 records &#215; 38 bytes, using an integer array:

`&,60,3,0,u%(0,0),**3*38,**dr$+"u.handles",dv%`

[start=4]
. drive prefix `dr$` + filename (the theoretical `u.handles`):

`&,60,3,0,u%(0,0),3*38,**dr$+"u.handles",**dv%`

[start=5]
. device `dv%`, set by `gosub 3` before the struct save call

---

=== `&,60,4` Put Date

Put an 11-digit date string into a struct (which is stored in 6 bytes as Binary Coded Decimal).

.Syntax
`&,60,4,0,` _struct%(field, record)_, _string$_

_struct%(field, record)_: struct name, record and field to store date in

.Parameters

_string$_: the 11-digit date string (either a literal string or string variable?) #FIXME#

.Returns
`?illegal quantity&#160;&#160;error` if the date string is not 11 digits

.Put Date Into Struct
[source,basic]
an$="10412208234":&,60,4,0,u%(3,0),an$
====

#TODO#: Explain example.

.Details: Binary Coded Decimal
****
Structs store an 11-digit date in 3 elements (6 bytes) using Binary Coded Decimal (BCD) format.
Two decimal digits are stored per byte, using the high and low _nybbles_ (_i.e._, 4-bit halves of an 8-bit number).

[source, basic]
an$="10412208234":&,60,4,0,u%(0,1),an$

[cols="8"]
[%autowidth]
|===
// 4 cells, cols 2-3, 4-5, 6-7 span
>|Element
2+^|`u%(0,1)`
2+^|`u%(0,2)`
2+^|`u%(0,3)`
>|_unused_

// 8 cells
>| Binary
^| `%0001&#160;%0000`
^| `%0100&#160;%0001`
^| `%0010&#160;%0010`
^| `%0000&#160;%1000`
^| `%0010&#160;%0011`
>| `%0100`
>| `%xxxx`

>| Decimal
>| `1&#160;&#160;&#160;&#160;&#160;&#160;0`
>| `4&#160;&#160;&#160;&#160;&#160;&#160;1`
>| `2&#160;&#160;&#160;&#160;&#160;&#160;2`
>| `0&#160;&#160;&#160;&#160;&#160;&#160;8`
>| `2&#160;&#160;&#160;&#160;&#160;&#160;3`
>|  `&#160;&#160;&#160;&#160;&#160;&#160;4`
>|  `&#160;&#160;&#160;&#160;x`
|===
****

'''

=== `&,60,5` Get Date

Convert a 6-byte Binary Coded Decimal (BCD) date string (as shown above) to the Image BBS 11-digit date format.

.&,60,5 Parameters

`&,60,5,0,` _struct%(field, record)_, _string$_

[%header]
[%autowidth]
|===
| Parameter | Purpose
| `&,60,5,0`,...
| Get date call. `0` seems to be an ignored but necessary parameter.

| `struct%(_field, record_)`,...
| struct name, field, record...

| _string$_
| ...string variable to hold the converted 11-digit date and time.
|===

.Get Date From Struct
[source,basic]
&,60,5,0,u%(0,1),an$:&,15:&an$

[%header]
[%autowidth]
|===
| Parameter | Purpose
| `&,60,5,0,`
| Get a date string...

| `u%(0,1),`
| ...from the struct `u%()`, record `1`, field `0`...

| `an$:`
| ...into the string `an$`.

| `&,15`
| Convert `an$` into a long date string.

| `&an$`
| Display the long date string.
|===

.Result
#TODO#: finish the output

'''

=== `&,60,6` Scan Struct

Test whether various conditions are met for each record in a struct.
The field to scan within each record is specified.
If the condition is met, add the record number to the specified array.
The number of fields meeting the condition is returned in the variable `a%`.

.Syntax
`&,60,6,` _num_, _command_, _a%(a,b)_, _b%(a,b)_, _size_, _bits_, _test_

////
;doscan - scan structures
; &,nn,6, num, com, a(a,b), b(a,b), l, bits, test
; num = # of structures to scan
; com = command number
; com = 0: 2 byte and, <>0
; com = 1: 2 byte and, ==0
; com = 2: 2 byte cmp, <
; com = 3: 2 byte cmp, >=
; com = 4: date cmp, <
; com = 5: date cmp, >=
; a(a,b) = starting flags element
; b(a,b) = starting object element
; l = unknown (rns)
; bits = the bits to set if true
; test = the object to test for
////

// 3166 a%=0:if s%(0,0) then:&,60,6,s%(0,0),0,s%(0,1),s%(1,1),80,1,2^ac%

.Parameters
[cols="1,2a"]
[%header]
|===
| Parameter | Purpose

| _num_
| The number of records to scan.

| _command_
| What to compare, using the following table:

// nested table
.Scan Struct Comparisons
[%autowidth]
[%header]
!===
! Command ! Purpose ! Add If Result
! 0 ! 2-byte `and` ! not equal to `0`
! 1 ! 2-byte `and` ! equal to `0`
! 2 ! 2-byte compare ! less than (`<`)
! 3 ! 2-byte compare ! greater than or equal to (`>=`)
! 4 ! date compare ! date is less than (`<`)
! 5 ! date compare ! date is greater than or equal to (`>=`)
!===

| _flag%(field,record)_
| Flag field

| _object%(field,record)_
| Object field

| _size_
| Record size in bytes

| _bits_
| The bits to set on `object%(a,b)` (?) if true?

| test
| x

|===

.&,60,6 Example

.i.GF: Scan Struct
[source,basic]
3166 a%=0:if s%(0,0) then:&,60,6, s%(0,0), 0, s%(0,1), s%(1,1), 80, 1, 2^ac%
3168 rn=a%:if rn then:&,60,8, s%(0,0), 80, 1, s%(0,1), e%(1), 1

[%header]
[%autowidth]
[cols="1,2,3a"]
|===
| Statement | Variable | Purpose

// `&,60,6,` _num_, _comparison_, _flag%(a,b)_, _object%(a,b)_, _size_, _bits_, _test_

| `3166 if s%(0,0) then...`
| _n/a_
| There is an implied `if s%(0,0)<>0` here, meaning "`if the record count is non-zero, then...`"

| `&,60,6,`...
| _n/a_
| scan struct command

| `s%(0,0),`...
| _num_
| for the record count

| `0,`...
| _comparison_
| `0`: 2-byte `and` between bits in `s%(0,1)` and `s%(1,1)`? #FIXME#

| `s%(0,1),`...
| _flag_
| flag struct name, record and field to get comparison data from (?)

| `s%(1,1),`...
| _object_
| object struct name, record and field to add matching record numbers to

| `80,`...
| _size_
| size of record in bytes

| `1`...
| _bits_
| bits to set if _command_ is true

| `2^ac%`
| _test_
| test object: here, the access level squared

|===

.i.MM.load: Scan Struct
[source,basic]
 4006 dr=3:gosub3:&,60,2,0,x1%(0,0),dr$+"e.Siglist",dv%:goto5
 4008 dr=3:gosub3:&,60,2,0,x3%(0,0),dr$+"e.Siglist"+str$(sg),dv%:goto5
 4100 q=.:a=12:gosub11:b=a:a=8:gosub11:ifa+bthenq=1
 4102 gosub4006:ife%<>0orx1%(0,0)=0then4146
 4104 xx=-(sy$="U/D")-2*(sy$="U/X"):f=4096+2^xx
 4106 &,60,6,x1%(0,0),0,x1%(0,1),x1%(1,1),36,4096,2^ac%
 4108 &,60,6,x1%(0,0),5,x1%(0,1),x1%(0,1),36,8192,f
 4110 &,60,6,x1%(0,0),7,x1%(0,1),x1%(0,1),36,16384,id
 4112 &,60,8,x1%(0,0),36,8192+16384,x1%(0,1),x2%(1),1:x2%(0)=a%
 4114 a$=left$(an$,2):an$=mid$(an$,3):ifa%=0then4146
 4116 ifa$=">>"ora$="<<"thenr=sg+1+2*(a$="<<"):on-(r<>0)goto4124
 4118 tz=0:gosub4004:on-(r<>0)goto4124:ifa%=1thenr=1:tz=1:goto4124
 4120 &"{f6}{wht} ##  SIG Name{f6}{f6}":fori=1tox2%(0):a%=i:x=x2%(i):&,60,1,30,x1%(3,x),b$
 4122 &"{wht}\#3\# \%a  {cyn}\$b{f6}":next:&"{wht}{f6}":p$="Which SIG?":gosub6:gosub4004
 4124 ifr<1orr>x2%(0)then4168
 4126 sg=x2%(r):r=0:so%=x1%(2,sg):&,60,1,30,x1%(3,sg),s$
 4128 sg$=s$:gosub4008:bz=0:ife%then4144

////
&,60,6, num, command, a%(a,b), b%(a,b), size, bits, test

The syntax has changed between the comments in the source code and i.UD line 3950
updated:
&,60,6, num, bits, a(a,b), b(a,b), size, command, test

Example:
&,60,6,rn,$80,x1%(0,1),x1%(0,1),60,2,2:c%=a%

x1%(0,1),x1%(0,1) -> reads field 0, record 1 and sets bit 7 on a match?
////

`num`: # of fields in the struct to scan

`bits`: the bits to set if _test_ is true

`flag%(_field, record_)`: the struct name, record and field on which to set `bits` if `test` is true.

====
NOTE: _record_ may be a dummy parameter, more tests needed.
====

* `and` does a logical and with the bits #FIXME#

* `cmp` compares values

_Add If Result_:: Add this record (field?) to the #FIXME# only if _object_ meets the command's criteria

_test_: the object to test for
(apparently can be either a variable or a number, maybe the byte number?)

.+.UD from Image 2.0
====
NOTE: This is still being researched.

The following code scans the U/D directory for entries which have an upload date older than `ld$`, setting bits `$4f` on `x1%(3,1)` (if the entry matches?):

////
Another version:
     &,60,6,rn,$80,x1%(0,1),x1%(0,1),60,2,2:c%=a%
////

.i.UD: Scan For Older Upload Date than ld$
[source,basic]
3950 &,60,6,rn,$4f,x1%(0,1),x1%(3,1),60,4,ld$:b%=a%

|===
| Parameter | Purpose

|`rn`
| highest record number to scan in the directory struct

|`$4f`
|(`%0100 1111` in binary) #FIXME# still researching the purpose of this

|`x1%(0,1)`
| Status bits?

|`x1%(3,1)`
| Upload date

|`60`
| each record is 60 bytes wide

|`4`
| date comparison: `<` (less than)

|`ld$`
| the comparison object (last call date).
Can apparently be a string name, or numeric: an array number?
|===

.Returns

`a%`: count of fields the comparison returns as matching `test`.

`b%(a,b)`: the array containing the comparisons matching `test` (?)

---

=== `&,60,7` Sort Struct

Sort a string array (only two-dimensional?).
Does not work with numeric arrays.

.Syntax

`&,60,7,0,` _a$(a, b)_, _start_

.Parameters

_a$(a,b)_: String array to sort

_start_: Element to start sorting at

.i/lo/tt maint: Sort Struct
====
[source,basic]
4016 for i=1 to 8:&".":&,60,7,0,a$(p+1,i),n-p:next:p=n-10
====

'''

=== `&,60,8` Scan Numbers

Scan through a specified field in a struct for non-zero values.
`a%` returns how many non-zero values there are.
The list of non-zero values are returned in the specified array.

.Syntax

`&,60,8,` _number_, _size_, _access_, _struct%(field, record)_, _result%(1)_, _start_

.Parameters

`number`: number of records to scan

`size`: size of the record, in bytes

`access`: access level to filter results by (in bits?)

`struct%(field, record)`: the struct, record and field to scan

`result%(1)`: the single-dimension array to put the results in.
`1` seems to be a dummy parameter: ignored, but necessary to be interpreted as a valid array reference.

`start`: record to start scanning at

.i/MM.load: Scan Numbers
[source,basic]
4112 &,60,8,x1%(0,0),36,8192+16384,x1%(0,1),x2%(1),1:x2%(0)=a%

[%header]
[%autowidth]
|===
| Parameter | Purpose
| `&,60,8`
| Scan Numbers sub-command

| `x1%(0,0)`
| number of records

| `36`
| the struct is 36 bytes per record

| `8192+16384`
| filter by bits 14/15 ($2000, `%00100000 00000000` + $4000, `%01000000 00000000`)

| `x1%(0,1)`
| look in the `x1%(field=_0_, record=1)` (field _0_="`don`'t care?`")

| `x2%(1)`
| put non-zero results in the `x2%()` array

| `1`
| Start at record 1.
|===

====
NOTE: More research needed.
`8192+16384` exceeds the expected access levels of 0-9 (values 1-1023).
====

.Example 2: i.UD
[source,basic]
3310 &,60,8,rn,60,a,x1%(0,1),f%(1),1:f%(0)=a%

// FIXME: order of params changed -- this is Jack's struct UD

. `&,60,8`: Scan Numbers sub-command
. `rn`: Scan through `rn` records
. `60`: the struct is 60 bytes per record
. `a`: filter by access level `a`
. `ud%(0,1)`: look in the `ud%(field=_0_, record=1)` (field _0_="don't care?")
. `f%(_x_)`: put non-zero results in the `f%()` array
. `1`: Start at record 1.

.Returns
`a%`: number of results returned, `0`=none.

`a%(a)`: one-dimensional array of results, from `a%(1--a)`

'''

=== `&,60,9` Scan Sum

.Syntax

`&,60,9,` _number_, _size_, _struct%(field, record)_

`number`: number of records to scan

`size`: size of record, in bytes

`struct%(field, record)`: (field="`don't care`"? #FIXME#), record to scan

====
NOTE: This function call documentation is incomplete.
====

.Example

None yet.

.Returns

`a%`: #FIXME#: total of values in struct?

'''

=== `&,60,10` Copy Record [[copy-record]]

Copy one record from one struct to a record in another struct.

.Syntax

`&,60,10,` _size_, _a1(a, b)_, _a2(a, b)_

.Parameters

`size`: size of record

`a1%(a,b)`: source struct `a1%()`, record `b` and field `a`

`a2%(a,b)`: destination struct `a2%()`, record `b` and field `a`

.i/IM.logon: Copy Record
====
[source,basic]
4694 if x<>fb%(.,.) then for a=x to fb%(.,.)-1:&,60,10,60,fb%(.,a+1),fb%(.,a):next
====

[%header]
[%autowidth]
|===
| Statement | Purpose
| `if x<>fb%(0,0)`
| if `x` does not equal the number of records in the struct [`fb%(0,0)`], then...

| `for a=x to fb%(.,.)-1`
| loop from `x` (the current record) to the number of records in the struct fb%() -1...
|===

=== `&,60,11` Scan for String

[%header]
[%autowidth]
|===
| Routine | Purpose
| `&,60,10,60,fb%(.,a+1),fb%(.,a)`
| copy 60-byte record `a+1` to record `a` in a loop.
|===

.i/GF-maint: Copy Record
[source]
4414 if br<>s%(0,0) then for a=br to s%(0,0)-1:&,60,10,80,s%(0,a+1),s%(0,a):next

[%header]
[%autowidth]
|===
| Routine | Purpose
| x
| x
|===

'''

=== `&,60,11` Scan for String

Scan struct for a string present in a specified field and record.
Put results (the indices of the fields the search results are found in) in the specified array.

.Syntax

`&,60,11,` _num_, _size_, _op_, _str_, _a1%(a,b)_, _a2%(b)_, _start_

.Parameters

`num`: number of records to scan

`size`: size of record

`op`: operation:

* `0` specifies a regular compare (a string literal)

* `1` specifies a pattern to match.
Here you can use two wildcard characters (like Commodore DOS):

** kbd:[f2] (in quote mode: kbd:[I]) is equal to kbd:[?], which specifies any character in its place
** kbd:[f7] (in quote mode: kbd:[H]) is equal to kbd:[*], which specifies any characters from this point to the end of the string

====
NOTE: You may only use the wildcard ``*`` following the specified string: ``text*``, not ``*text``.
====

`str`: string variable or string literal to scan for

`a1%(a,b)`: source struct _a1%()_, record _b_, field _a_, to scan

`a2%(b)`: target 1-dimension array _a2%()_, dummy element _b_, to put results into

`start`: record to start scanning from

.Returns

`a%`: the count of results returned, `0` if none.

`a2%(b)`: the array of results; each element is a search result

.Example

None yet.

'''

=== `&,60,12` Game Scan

Unknown purpose.

.Syntax

`&,60,12,` _count_, _size_, _a$_, _a%(a,b)_, _b$_

.Parameters

`count`: how many records to scan?

`size`: size of the record to scan

`a$`: a string to search for?

`a%(a,b)`: `a%()`: struct name, `a`: field and `b`: record to scan

`b$`: ?

.Example

None yet.

7'''

=== `&,60,13` Text Read

Not sure yet. Read a file into a struct?

.Syntax

`&,60,13,` _number,_ _reclen,_ _scan(),_ _bits,_ _text(),_ _strlen_

// either that, or:
// game scan
// &,60,13,count,size,a$,a%(a,b),b$

.Parameters

_number,_: count of lines to read?

_reclen,_: record length?

_scan(),_: ?

_bits,_: ?

_text(),_: ?

_strlen_: ?

.Example

None yet.
