:experimental:
:toc:

## Set Up Image BBS 3.0

Setting up your BBS should be very simple, as long as you follow the instructions.
We suggest you read this chapter carefully and then set up your system step by step, keeping the manual handy for reference.

// The configuration section also has built in help to get you configured fast and easily.

### Supported Hardware

Image BBS v3.0 was tested on the following hardware:

* WinVice using both 1581 and FD4000 disk drives, normal User Port communications with both `tcpser` and BBS Server/VSPE configurations.

* Lt. Kernal (or Rear Admiral) hard drive with SwiftLink or normal User Port configurations using BBS Server as the "`modem`".

* Creative Micro Designs`' (or ThunderDrive) Hard Drive with SwiftLink, and normal User Port configurations using BBS Server as the "`modem`".

* &micro;IEC/SD by Jim Brain as a mass storage device.

Although we have not tested this software on a great deal of other hardware, it should run with no issues on just about any hardware.

### Get Started

Now that you are ready to set up your IMAGE BBS, we recommend that the first thing you do is back up the file(s) you received the BBS software in, then keep them in a safe place.
Copying the files out of the original disk images we recommend you use `fcopy+` for all the PRG and SEQ files, and `copy-all.64l` written by Jim Butterfield for the REL files.

### Designate Drives

The Commodore 64 is designed to use up to eight devices on the serial port.
However, we recommend not using more than six due to current limitations of the serial port driver.
It will support single or dual drives, or logical units (LU`'s) 0 through 9 on a Lt. Kernal (IMAGE will not access LU 10 on a Lt. Kernal).
You will want to plan your setup on what space you have available, so read the following information carefully to help you in this regard. 
Although it is possible to run IMAGE BBS v3.0 using only two 1581 disk drives, we highly recommend you use multiple drives, since you will find that disk space and directory space gets used quickly.

_Device_ refers to either the physical unit, or the device number(s) assigned to the particular device (_i.e._ one device online is usually set to 8, two devices to 8 and 9, etc.).

#FIXME# - is this a decent description?
_Drive_ refers to the number of available separate storage spaces available on a device.

- 0 on a single drive (such as a 1541 or 1571--the count begins at zero)
- 0 or 1 on a dual drive (such as a 2031)
- _Logical Units:_ 0 through 9 on a Lt. Kernal or Rear Admiral hard drive
- _Partitions:_ 1 through 254 on a Creative Micro Designs (or ThunderDrive)

If you have multiple devices connected, there may either be a switch somewhere on the device to change the device number, or--in the case of CMD and Rear Admiral drives--a "`Swap`" button to change the device number in software.

_Directory space_ refers to the number of directory entries possible on the drive. The limit depends on the type of disk drive.
A 1581 drive allows 296 directory entries, while an SFD 1001 allows 224, etc.
Check your drive manual to see what the limitation is.

#TODO# 1541 limit? LtK limit? Other limits?

_Drive space_ refers to blocks used, while _blocks free_ refers to blocks unused on the drive.

#### Image Drive Numbers

The terms _Image drive_ or _system disk_ refer to six categories of files used by Image BBS for system functions.
They are referred to by the numbers 1-6, since standard Commodore device numbers less than 8 are not typically used.

TIP: _Technically,_ device 0 is the keyboard, 1 is the Datasette, 2 is user port RS232, 3 is the screen, 4-5 are printers, and 6 is a plotter.

Each Image drive may be assigned to separate disks, LUs or partitions.
Or, several Image drives can be combined onto a single disk, LU or partition.
Your drive layout will depend on the type and capacity of your storage device(s).

The six Image drives are described as follows:

[start=1]
. The "`System Disk`"

System files are mostly SEQuential (text) files that do _not_ change often.
Menu files, board entry files, and board data files are all included on this disk.
Will not use too much directory or drive space.

System files have a prefix of `s.`.

Also, system news files are located here.
News files have a prefix of `n.`.

[start=2]
. The "`E-Mail Disk`"

E-Mail files contain all user e-mail messages.
_Forced mail_, e-mail messages that are not optional to view (and can contain various user account manipulation directives), are also stored here.
These use much more directory space than disk space.

E-mail files have a prefix of `m.`.

Forced mail files have a prefix of `f.`.

If the BBS is networked, network mail and network configuration files have a prefix of `nm.`.

[start=3]
. The "`Etcetera Disk`"

Etcetera files are miscellaneous files used to supply the system with information.
Many online games and functions use one or more Etcetera files to store data.
Some of these files are RELative files, and most of them change frequently.
Storage space depends on the number and type of online games or programs you are using.
If no online programs use the Etcetera disk, it will not use too much disk or directory space.

Etcetera files have a prefix of `e.`.

[start=4]
. The "`Directory Disk`"

Directory files group related information into a single file, like a disk directory does.
Whether the information is the posts and responses for a particular sub-board, file information in a U/D or U/X library, or modules in a General File library, a directory file helps the BBS index information.
These files change often, and this disk will use a fair amount of directory space, but not too much disk space.

Directory files have a prefix of `d.`.

[start=5]
. The "`Program Disk`"

The Program Disk contains module files--BASIC or ML programs--that load in when needed to execute functions.
They are the main "`operating system`" of the BBS.

These files have several prefixes (`i`, `sub.` and `++`), explained in more detail in the <<modules.adoc#Module Types,Module Types>>  section of this manual.

They do not change, unless modified offline. 

// inter-document cross-ref: filename, section, xref text
// <<document-b.adoc#section-b,Section B>>

These are all the files found on the `IMAGE 3.0 D1` disk.

[start=6]
. The "`User Disk`"

User files contain data about the people on your BBS.
As new users sign up, the user file is expanded.

There is one REL file (`u.config`) and two PRG files (`u.index` and `u.weedinfo`) that keep all user information available to the system.
There are three directory entries, a little over one block per user total.

NOTE: Device and drive numbers other than the six Image drives can be assigned to individual sub-boards in the `SB` section, U/D or U/X libraries in the `UD` or `UX` sections, and items in the `GF` section (games, text files, movie files, etc.).
As an example, you can assign a movie file entry in the `GF` section to device 11, drive 6 instead of Image drive 1 (the `s.` disk) if you had more storage space available there, or wanted to put your movie files on a separate partition.

## Configuration Options

Image 3.0 has three methods of installation:

kbd:[1] Configure a New BBS

kbd:[2] Convert from 1.2

kbd:[3] Convert from 2.0

kbd:[4] Abort
    
Option kbd:[4] is there in case you change your mind--it does a C64 cold start.

Each method is explained separately.
Please refer to the installation instructions for the method you intend to use.

NOTE: There are <<Shared Image BBS 3.0 Setup>> steps to take no matter if you are upgrading from a previous version or a new install.

### Configure a New BBS

1.	Configure your hard drive and/or other system hardware for your Image drive assignments.

It`'s recommended that you:

- Use separate partitions or drives for Image drives 1 (System), 2 (Mail), and 5 (Program)
- Combine 3 (Etcetera), 4 (Directory) and 6 (User) drives to 
a different drive or partition.

You'll probably want two additional drives or partitions for message boards and Upload/Download sections.

[start=2]
2.	Either convert the three .d81 and two .d64 files to floppy disk or use some other method of getting the files onto your Image drives.

3.	Use `fcopy+` included on the 3.0 UTILS disk for copying all the files from disk 1 to your "`Program Disk`". 

4. 	It's recommended to use `copy-all.64l`, also included on the 3.0 UTILS disk, for copying all the `e.` files from disk 2 to your "`Etcetera Disk`".

5.	Use `fcopy+` to copy all the `s.` files to your "`System Disk`" and the `nm.times` file to your "`E-Mail Disk`".

TIP: If you wish to run the Today in History logon module, copy all the `today.*` files to your "`Etcetera Disk`".

[start=6]
include::includes\sub_modem-config.adoc[]

### Installation

1.	Access the device and drive of your "`Program Disk`" then type: `load"boot",_x_,1`  (_x_= device # of your boot drive)
2.  When prompted type kbd:[1] to Configure a New BBS.  
3.	Image begins collecting information needed to configure 3.0.
4.	Part I: Sysop Information

Enter the information asked for. 

[start=5]
5.	Part II: Clock Setting

You are asked to select a method of setting the system clock automatically during boot up.

kbd:[1] Manually

You need to set the date and time after every reboot.

kbd:[2] CMD Device w/RTC Option

You are asked which device has the Creative Micro Designs Real-Time Clock option.
Enter the device number of your CMD device.

kbd:[3] Lt. Kernal Port 1

kbd:[4] Lt. Kernal Port 2

These are for use with Lloyd Sponenburgh’s Real-Time Clock module attached.

[start=6]
6.	Part III: Device/Drive Settings

Configure your Image drive assignments.

[start=7]
7.	Part IV: BBS Information

Enter the customized information asked for pertaining to your BBS.

NOTE: Seems like this part could be folded into <<Shared Image BBS 3.0 Setup>>. I'm not sure if the conversion process follows these steps exactly.

At this point, Image creates several files needed for its own operation.
When finished, Image displays a message for you to read and asks you to `Hit any key`.

You are then prompted for the RS232 interface type you have connected to the C64.

- If you have an OmniTronix or similar user port interface, type kbd:[0].

- If you have a SwiftLink, Turbo232, or a clone of these on the cartridge port, type kbd:[1].

Hit a key, and you are taken to the System Idle screen.

### Set the Clock

* If the time has been set using a real-time clock, Image performs AutoMaintenance.

* If not already set by a real-time clock, the bottom Status Line continues to flash until the time is set.
Hit kbd:[1] to set the time.
You are taken through several prompts to set the time and date:

[start=1]
. Weekday

.Weekday Numbers
[options="header,autowidth"]
|====================
| Number | Day  
| kbd:[1] | Sunday  
| kbd:[2] | Monday  
| kbd:[3] | Tuesday 
| kbd:[4] | Wednesday
| kbd:[5] | Thursday
| kbd:[6] | Friday  
| kbd:[7] | Saturday
|====================

[start=2]
. Year

Enter only the last two digits of the year here.

[start=3]
. Month

[start=4]
. Day

[start=5]
. Hour

[start=6]
. Minute

The current date and time is displayed, and you are prompted `Select Yes to Start Clock, or Select No to Change`.

kbd:[Y]es logs the time and date to `e.data` and sets the system clock.

kbd:[N]o restarts the clock setting questions.

Image may or my not perform AutoMaintenance again and return to the System Idle screen.

### Instant Login

#FIXME#: I don`'t think hitting f1 to go to full screen mode will let you hit f7. I might be wrong.

[start=2]
2.	#Press kbd:[f1] to go to full screen mode then# 
Use kbd:[f3] and kbd:[f5] to make sure the lightbar highlight is on `Loc`, then press kbd:[f7] to put a check mark on the left of `Loc`. This starts a console BBS login.

3. Press kbd:[I] for Instant Login. 

3.	When asked, type your sysop password.

### Configuration

The BBS greets you with a welcome message and prompts you to select your time zone.

. Select your time zone (7=EST, 6=CST, 5=MST, 4=PST)
. The BBS will display the current time and `Stack Free: 239`.

NOTE: Any `Stack Free` number less than 239 at the Main Prompt means there is garbage (`GOSUB` without `RETURN`, or `FOR` without `NEXT` statements) on the stack. 

[start=3]
.	At the Main Prompt, type kbd:[EP] to _Edit your Parameters_. 
Select kbd:[P]arameters.

. Set your Computer Type and any other Terminal Parameters you want. 

_More? Prompt_ Off and _Cursor Menu Mode_ On are recommended.

Hit kbd:[Return] to exit.

[start=5]
. At this point, it is suggested you log off using the kbd:[O] command and answer `Update User File?` with kbd:[Y]es.
This will save your new parameters to your user file.
You can then log back on in any mode you choose. 

IMPORTANT:  Always log off with the kbd:[O], kbd:[O!] or kbd:[O%!] commands.
Logging off by hitting kbd:[f7] (unchecking left `Loc`) will bypass the module which updates the last 10 callers and cause errors in the time used during the call.

#### Shared Image BBS 3.0 Setup

These steps are followed if you`'re upgrading from a previous version or setting up a new Image BBS.
They help set up features specific to Image 3.0.

. Log back on to the BBS.
. At the Main Prompt, type kbd:[IM].
You are taken to the Image BBS Configuration Editor.

##### Access Groups

You can use the cursor keys to move the highlight, or type kbd:[E] for `Access Groups`.
The BBS will load the access group information.

[width="100%"]
|====================
| #TODO:# Why not change `i/su.config` to do this:
|====================

// Duplicated at line 460.

The Group 9 flags should already be set for full sysop access.
Type kbd:[9] and change the group name to `Sysop`.

Edit any access group Name and Flags per your preference. 
kbd:[Return] exits, saving changes.
You are returned to the Configuration Editor.

. Type kbd:[I] for ``Misc. Features``.
.. At minimum, you will need to set the Time Zone and the System ID.
..  If you are running on a Lt. Kernal, use option kbd:[A] to set to your Lt. Kernal device number.
.. Enter kbd:[M] to configure your Chat messages for entering and leaving chat.
.. Edit any other parameter you wish to set.
.. When finished, type kbd:[N] to `Quit` back to the Configuration Editor.

#### Modem Configuration

. Type kbd:[J] for `Modem Config`.
.. Type kbd:[B] for `Setup/Import Modem Config`.
.. Type kbd:[1] for `Setup New Modem Config`.
.. Answer kbd:[Y]es to the next two questions. #FIXME#: what are they?

### GGlabs GLink232-LT

The following will guide you through how to set up a GGlabs GLink232-LT interface connected to BBS Server.

include::includes\im-gglabs-modem-config.adoc[]

NOTE: If using ESCape codes, you will need to modify `sub.modem` as stated in item 6 under <<Configure a New BBS>>.

When finished configuring your modem, type kbd:[X] to `Exit Modem Config` and answer `Update Modem Flags?` kbd:[Y]es.

The remaining configuration options are custom settings for your BBS and will not be discussed as part of the installation process.

## Introducing RELedit

RELedit, if you're not familiar, is #FIXME#. For more information, see the chapter on RELedit.

.	Type kbd:[N] to go to the `Base Editors`.

.	Cursor to or type kbd:[G] for `Editor Utils`.

.	Type kbd:[A] to `Run RELedit`.
Here you will define your Subs, U/Ds, U/Xs and SIGs the same way it is done in Image 1.2a.
You _must_ define at least one SIG and add your SB, UD and UX assignments.

When finished with RELedit, exit using the kbd:[Return] key until you end up back at the `Base Editor` menu.

The remaining items in the `Base Editor` menu are sysop utilities for maintaining the BBS.

#TODO#: Refer to the IM Configuration Editor chapter for further information.

17.	Select kbd:[K] to return to the Configuration Editor.

18.	Select kbd:[Q] to exit the menu back to the Main Prompt. 

19.	Refer to <<final-notes>> for further instructions.

### Conclusion

From here, explore and become familiar with the new features. 

Much has changed since Image 1.2 and 2.0. The best way to learn is to experiment.

You`'ll probably be confused and make mistakes along the way, but the learning experience is necessary for any new system.

#FIXME#: that's not helpful wording. We don't want documentation to be user-hostile. -rs

// Cross-reference [[cross-reference]] set.
// a <<cross-reference,cross-reference>> mentioned.

More information is provided in the #TODO# Sysop Guide section, but one of the main objectives of Image 3.0 is to make it as sysop- and user-friendly as possible. 

As in previous versions of Image BBS software, menus are displayed with kbd:[?] and a Local Command menu is displayed to level 9 users with pseudo-Local mode access by typing kbd:[??].

### Configuration

NOTE: Duplicate section. Old formatting.

1.	At the System Idle screen, hit the number 1 key to set the time. Image will perform auto maintenance and return to the Idle screen.
2.	Press the f1 key to go to full screen mode then press the f7 key to log on. Press the "`I`" key for Instant Login. 
3.	If asked, type your password. The BBS will greet you with a welcome message and then prompt you to select your time zone.
4.	Select your time zone (7=EST, 6=CST, 5=MST, 4=PST)
5.	Enter the number of lines per screen (suggest 23)
6.	At the Main Prompt, type kbd:[EP] to Edit your Parameters. 
a.	Select kbd:[P]arameters.
b.	Set your Computer Type and any other Terminal Parameters you want. 
c.	(_Optional_) Set Cursor Menu Mode On.
d.	Hit kbd:[Return] to exit.
e.	At the Main Prompt, type kbd:[EP] to Edit your Parameters. 
f.	Select kbd:[I]nfo.
g.	Change your phone number to your email address.
h.	Type kbd:[Return] to exit.
7.	At this point, it is suggested you log off using the kbd:[O] command and answer `Update User File?` with kbd:[Y]es. This saves the new parameters to your account. You can then log back on in any mode you choose.

NOTE: Always log off with the kbd:[O], kbd:[O!] or kbd:[O%!] command.
Logging off with the kbd:[f7] key will bypass the module which updates the last 10 callers and cause errors in the time used.

[start=8]
.	Log back on to the BBS. At the Main Prompt, type kbd:[IM].

You are taken to the Image BBS Configuration Editor.

[start=9]
.	You can use cursor controls or just type kbd:[E] for `Access Groups`.
All group names and flags should be the same as your 1.2 system was.
Edit any access group Name and Flags per your preference.

Type kbd:[Return] to exit, saving changes.
You are returned to the Configuration Editor.

[start=10]
.	Enter kbd:[I] for `Misc. Features`.

.. At minimum, you will need to set the `Time Zone` and the `System ID`.
.. If you are running on a Lt. Kernal, use option kbd:[A] to set to your Lt. Kernal device number.
.. Type kbd:[M] to configure your Entering and Exiting Chat messages.
.. Edit any other parameters you wish to set.
.. When finished, type kbd:[N] to `Quit` back to the Configuration Editor.

[start=11]
11.	Enter J for Modem Config. Enter B for Setup/Import Modem Config.  Enter 1 to Setup New Modem Config.  Answer Yes to the next two questions.

include::im-gglabs-modem-config.adoc[]

12. Type kbd:[D] to enter the `Logon Editor` sub-menu.
13.	Type kbd:[A] for `Logon Mods`.
.. Type kbd:[H]elp for instructions on how to configure your logon modules.
.. Configure them for your preference.

IMPORTANT: Since this is a conversion from 1.2 to 3.0, it`'s highly recommended you include `i/lo-email` as a forced module in your login mods.
This asks any user whose account is still configured with a phone number to change it to an email address.

[start=14]
.	Type kbd:[B] for `Maint Mods` to configure your nightly AutoMaintenance modules.
2.	Configure any other items you need to get started.
3.	When back at the Configuration Editor, type kbd:[N] for `Base Editors`.
4.	Cursor to or type kbd:[G] for `Editor Utils`.
5.	Enter kbd:[A] to `Run RELedit`. Here you should find your Subs, U/Ds, U/Xs and SIGs the same way it was configured in Image 1.2a.

Verify everything is correct or make changes as needed.
If your 1.2 system was networked, you will need to go into each netsub you have defined.
No changes need to be made from within the netsub but when you exit each netsub, they are updated to a new Image 3.0 file format called a "`structure file.`"

When finished with RELedit, exit with kbd:[Return].
The BBS performs a series of operations to convert all your 1.2 SIGs to 3.0 format.
When finished, you go back to the `Base Editor` Menu.

[start=6]
6.	This would be a good time to check your CMD Clock and Set Time Device number of your CMD drive if you want to use it for setting Image time during boot-up.
Use the available menu selections.

7.	Type kbd:[K] to quit back to the Configuration Editor.

8.	Type kbd:[Q] to quit back to the Main Prompt.

9.	If you had macros defined in your 1.2 system and want to keep them, you will need to convert the `e.macros` file. Otherwise, just delete it.

If you would like to convert the file, follow these steps:

#FIXME# more exact steps.

.. Use kbd:[RD] at the Main Prompt, and read the SEQuential file `e.i.macros`.
This contains the number of macros you have.
.. Use kbd:[RF] at the Main Prompt. This is a RELative File editor.
.. Select `e.macros`.
.. kbd:[V]iew record 1.

TIP: You might want to move this record to the end of the file, since it will be replaced by the macro count.

[start=5]
.. Edit record 1, replacing the data in it with a number equal to 1 less than the number of macros in `e.i.macros`.
.. You can then use kbd:[DC] to scratch `e.i.macros`, since it is not needed anymore.

[start=22]
22.	Read the <<final-notes>> on the last page of these instructions.

From here, explore and become familiar with the new features. 
Much has changed since Image 1.2 and 2.0.
The best way to learn is to experiment.
You`'ll probably be confused and make mistakes along the way but the learning experience is necessary for any new system.
More information is provided in the #TODO# Sysop Guide section but one of the main objectives of Image 3.0 is to make it as user-friendly as possible. 

As in previous versions of Image BBS software, menus are displayed with kbd:[?], and a Local Command menu is displayed to level 9 users with pseudo-Local mode access by entering kbd:[??].


## Final Notes [[final-notes]]

Included in the Image 3.0 package is a games disk containing several ready-to-install games converted to Image 3.0 format.
Load and run the `run me` file (Image SEQ Reader) which will allow you to read the installation instructions for all the games included on the disk.

Also included in the Image 3.0 package is a weed mod disk.
Load and run the `run me` file (Image SEQ Reader) which will allow you to read the installation instructions for all the files included on the disk.

#TODO:# Explain what this is.

In Image 3.0, the GF section replaces the Image 1.2 `PF`, `TF`, `NF` and `RF` sections.
To go there, enter kbd:[GF] at the Main Prompt.
If you`'re in Maintenance Mode with Graphic Menus on, you will see a list of sysop options for editing the menus.
It was designed to be sysop friendly and anyone with a little Image 1.2 knowledge should be able to navigate through the functions to get items added to the GF section. 

These instructions were written for real hardware but Image 3.0 will run well in WinVice.
In fact, much of the development and testing of this software was done in VICE. 

Enjoy the files.
Many thousand man-hours have gone into their creation and what they are today.

I will answer questions and provide tech support for this software as needed.
Contact X-TEC at node 1 of the NISSA Network.

[.text-right]
Larry Hedman
[.text-right]
Al DeRosa
