:experimental:
:toc:

## Setting Up Image BBS 3.0

Setting up your BBS should be very simple, as long as you follow the instructions.
We suggest you read this chapter carefully and then set up your system step by step, keeping the manual handy for reference.

// The configuration section also has built in help to get you configured fast and easily.

### Hardware Considerations

Image BBS v3.0 was tested on the following hardware:

* WinVice using both 1581 and FD4000 disk drives, normal User Port communications with both `tcpser` and BBS Server/VSPE configurations.

* Lt. Kernal (or Rear Admiral) hard drive with SwiftLink or normal User Port configurations using BBS Server as the "`modem`".

* Creative Micro Designs`' (or ThunderDrive) Hard Drive with SwiftLink, and normal User Port configurations using BBS Server as the "`modem`".

* &micro;IEC/SD by Jim Brain as a mass storage device.

Although we have not tested this software on a great deal of other hardware, it should run with no issues on just about any hardware.

### Getting Started

Now that you are ready to set up your IMAGE BBS, we recommend that the first thing you do is back up the file(s) you received the BBS software in, then keep them in a safe place.
Copying the files out of the original disk images we recommend you use `fcopy+` for all the PRG and SEQ files, and `copy-all.64l` written by Jim Butterfield for the REL files.

### Designating Drives

The Commodore 64 is designed to use up to eight devices on the serial port.
However, we recommend not using more than six due to current limitations of the serial port driver.
It will support single or dual drives, or logical units (LU`'s) 0 through 9 on a Lt. Kernal (IMAGE will not access LU 10 on a Lt. Kernal).
You will want to plan your setup on what space you have available, so read the following information carefully to help you in this regard. 
Although it is possible to run IMAGE BBS v3.0 using only two 1581 disk drives, we highly recommend you use multiple drives, since you will find that disk space and directory space gets used quickly.
When referring to "`device`" in this chapter, we are talking about the device number assigned to the particular drive (_i.e._ one drive online is usually set to device 8, two to 8 and 9, etc.).

When referring to "`drive`", we are talking about the drive number.
(0 on a single drive, 0 or 1 on a dual drive, 0 through 9 on a Lt. Kernal hard drive, 1 through 254 on a CMD HD or ThunderDrive).
If you have multiple drives, there may either be a switch somewhere on the drives to change device numbers, or in the case of CMD and Rear Admiral drives, a "`Swap`" button in addition to rear panel switches. 

"`Directory space`" refers to the number of directory entries possible on the drive, which is usually limited, depending on the type of disk drive.
A 1581 drive allows 296 directory entries, while an SFD allows 224, etc.
Check your drive manual to see what the limitation is.
"`Drive space`" or "`blocks free`" mentioned here will refer to actual blocks used/unused on the drive.

#### Image Drive Numbers

The term "`Image drive`" refers to six categories of files used by Image BBS for system functions.
Each Image drive may be assigned to separate disks or partitions, or several Image drives can be combined onto a single disk or partition.
Your drive layout will depend on the type and capacity of your storage devices.

The six "`Image drives`" are described as follows:

[start=1]
. The "`System Disk`"

Contains mostly SEQuential (text) files that do _not_ change often.
Menu files, board entry files, and board data files are all included on this disk.
Also, system news files are located here.
Will not use too much directory or drive space.
Most files on this disk have a prefix of `s.`, except news files, which are prefixed with `n.`.

[start=2]
. The "`E-Mail Disk`"

Contains all user e-mail and forced mail files.
Will use much more directory space than disk space.
All mail files have a prefix of `m.`, while forced mail files have a prefix of `f.`.
If the BBS is networked, network mail files with a prefix of `nm.` are also stored here.

[start=3]
. The "`Etcetera Disk`"

All files on this disk are prefixed with `e.`.
They contain miscellaneous files used to supply the system with information.
Many online games and functions use one or more `e.` files to store data.
Some of these files are RELative files, and most of them change frequently.
Storage depends on the number and type of online games and programs you are using.
If no online programs use the Etcetera disk, it will not use too much disk or directory space.

[start=4]
. The "`Directory Disk`"

Contains all directories used on the system, whether for sub-boards, U/D libraries, general file libraries, or whatever.
These files have a prefix of `d.`.
These files change often, and this disk will use a fair amount of directory space, but not too much disk space.

[start=5]
. The "`Program Disk`"

Contains module files--BASIC or ML programs--that load in when needed to execute functions.
They are the main operating system of the BBS and use several prefixes (`i`, `sub.` and `++`) which are explained in more detail in the #TODO# Sysop Guide section of this manual.
They do not change, unless modified offline. 

These are all the files found on the `IMAGE 3.0 D1` disk.

[start=6]
. The "`User Disk`"

Contains all user data files, which are expanded as needed.
There is one REL file (`u.config`) and two PRG files (`u.index` and `u.weedinfo`) that keep all user information available to the system.
Three directory entries, a little over one block per user total.

NOTE: Device and drive numbers other than the six Image drives can be assigned to individual sub-boards in the SB section, U/D or U/X libraries in the U/D or U/X sections, and items in the GF section (games, text files, movie files, etc).
As an example, you can assign a movie file entry in the GF section to device 11, drive 6 instead of Image drive 1 (the `s.` disk) if you had more storage space available there, or wanted to put your movie files on a separate partition.

## Configuration Options

Image 3.0 has three methods of installation:

    1. Configure a New BBS
    2. Convert from 1.2
    3. Convert from 2.0
    4. Abort
    
Option `4` is there in case you change your mind--it does a C64 cold start.

Each method is explained separately.
Please refer to the installation instructions for the method you intend to use.

NOTE: There are <<shared-setup-steps>> to take no matter if you are upgrading from a previous version or a new install.

### Installing a New System

1.	Configure your hard drive and/or other system hardware for your Image drive assignments.
It's recommended you use separate partitions or drives for Image drives 1 (System), 2 (Mail), 5 (Program) and combining 3 (Etcetera), 4 (Directory) and 6 (User) drives to a different drive or partition.
You'll probably want two additional drives or partitions for message boards and Upload/Download sections.

2.	Either convert the three .d81 and two .d64 files to floppy disk or use some other method of getting the files onto your Image drives.

3.	Use `fcopy+` included on the 3.0 UTILS disk for copying all the files from disk 1 to your "`Program Disk`". 

4. 	I recommend using COPY-ALL.64L, also included on the 3.0 UTILS disk, for copying all the `e.` files from disk 2 to your "`Etcetera Disk`".

5.	Use `fcopy+` to copy all the `s.` files to your "`System Disk`" and the `nm.times` file to your "`E-Mail Disk`".

TIP: If you wish to run the Today in History logon module, copy all the `today.*` files to your "`Etcetera Disk`".

[start=6]
6. The file `sub.modem` is customized for use with BBS Server using DTR as carrier detect.
Line 60080 contains `print#131,chr$(27)` for setting the Hayes AT escape character to Escape (this was done to avoid BBS Server hanging up when it saw `+++`).

NOTE: If you are using a virtual modem such as `tcpser` and need to use escape codes instead of DTR for disconnecting the caller from the BBS, you may need to change the 27 (`Escape`) to 43 (`+`) and set `ats2=43`.

[start=7]
7.	Line 3082 in `im` is preconfigured for running Image 3.0 from the user port.
If you intend to use a SwiftLink, Turbo232, or a clone of these on the cartridge port, change `&,16,.` (which initializes user port RS232) at the end of that line to `&,16,1` (this initializes cartridge port RS232 instead).

### Installation

1.	Access the device and drive of your "`Program Disk`" then type: `load"boot",_x_,1`  (_x_= device # of your boot drive)
2.  When prompted type kbd:[1] to Configure a New BBS.  
3.	Image begins collecting information needed to configure 3.0.
4.	Part I: Sysop Information - Enter the information asked for. 
5.	Part II: Clock Setting - You are asked to select a method of setting the system clock automatically during boot up.

kbd:[1] Manually

kbd:[2] CMD Device w/RTC Option

kbd:[3] Lt. Kernal Port 1

kbd:[4] Lt. Kernal Port 2

If you select kbd:[1], you need to set the date and time after every reboot.

If you select kbd:[2], you are asked which device has the Creative Micro Designs Real-Time Clock option. Enter the device number of your CMD device.

Options kbd:[3] and kbd:[4] are for use with Lloyd Sponenburgh’s Real-Time Clock module attached.

[start=6]
6.	Part III: Device/Drive Settings

Configure your Image Drive assignments.

[start=7]
7.	Part IV:  BBS Information

Enter the customized information asked for pertaining to your BBS.

At this point, Image creates several files needed for its own operation.
When finished, Image displays a message for you to read and asks you to `Hit any key`.
Hit a key, and you are taken to the System Idle  screen.

### Set the Clock

* If the time has been set using a real-time clock, Image performs AutoMaintenance.

* If not already set by a real-time clock, the Bottom Status Line continues to flash until the time is set.
Hit kbd:[1] to set the time. You are taken through several prompts to set the time and date.

[start=1]
. Weekday

.Weekday Numbers
[options="header,autowidth"]
|====================
| Number | Day  
| kbd:[1] | Sunday  
| kbd:[2] | Monday  
| kbd:[3] | Tuesday 
| kbd:[4] | Wednesday
| kbd:[5] | Thursday
| kbd:[6] | Friday  
| kbd:[7] | Saturday
|====================

[start=2]
. Year

[start=3]
. Month

[start=4]
. Day

[start=5]
. Hour

[start=6]
. Minute

You are prompted `Select No ... or Yes to start clock`. #FIXME#

kbd:[Y]es logs the time and date to `e.data` and sets the system clock.

kbd:[N]o restarts the clock setting questions.


Image may or my not perform AutoMaintenance again and return to the System Idle screen.

### Instant Login

#FIXME#: I don`'t think hitting f1 to go to full screen mode will let you hit f7. I might be wrong.

[start=2]
2.	#Press kbd:[f1] to go to full screen mode then# 
Use kbd:[f3] and kbd:[f5] to make sure the lightbar highlight is on `Loc`, then press kbd:[f7] to put a check mark on the left of `Loc`. This starts a console BBS login.

3. Press kbd:[I] for Instant Login. 

3.	When asked, type your sysop password.

### Configuration

The BBS greets you with a welcome message and prompts you to select your time zone.

. Select your time zone (7=EST, 6=CST, 5=MST, 4=PST)
. The BBS will display the current time and `Stack Free: 239`.

NOTE: Any `Stack Free` number less than 239 at the main prompt means there is garbage (`GOSUB` without `RETURN`, or `FOR` without `NEXT` statements) on the stack. 

[start=3]
.	At the main prompt, type kbd:[EP] to _Edit your Parameters_. 
Select kbd:[P]arameters.

. Set your Computer Type and any other Terminal Parameters you want. 

_More? Prompt_ Off and _Cursor Menu Mode_ On are recommended.

Hit kbd:[Return] to exit.

[start=5]
5.	At this point, it is suggested you log off using the kbd:[O] command and answer `Update User File?` with kbd:[Y]es.
This will save your new parameters to your user file.
You can then log back on in any mode you choose. 

IMPORTANT:  Always log off with the kbd:[O], kbd:[O!] or kbd:[O%!] commands.
Logging off by hitting kbd:[f7] (unchecking left `Loc`) will bypass the module which updates the last 10 callers and cause errors in the time used.

### Image BBS 3.0 Setup Steps [[shared-setup-steps]]

These steps are followed if  you`'re upgrading from a previous version or setting up a new Image BBS.
They help set up features specific to Image 3.0.

. Log back on to the BBS.
. At the main prompt, type kbd:[IM].
You are taken to the Image BBS Configuration Editor.

#### Access Groups

You can use the cursor keys to move the highlight, or type kbd:[E] for Access Groups.
The BBS will load the access group information.

[width="100%"]
|====================
| #TODO:# Why not change `i/su.config` to do this:
|====================

TIP: Duplicated at line 460.

The Group 9 flags should already be set for full sysop access.
Type kbd:[9] and change the group name to `Sysop`.

Edit any access group Name and Flags per your preference. 
kbd:[Return] exits, saving changes.
You are returned to the Configuration Editor.

. Type kbd:[I] for _Misc. Features_.
.. At minimum, you will need to set the Time Zone and the System ID.
..  If you are running on a Lt. Kernal, use option A to set to your Lt. Kernal device number.
.. Enter M to configure your Chat messages for entering and leaving chat.
.. Edit any other parameter you wish to set.
.. When finished, type kbd:[N] to Quit back to the Configuration Editor.

#### Modem Configuration

. Type kbd:[J] for Modem Config.
.. Type kbd:[B] for Setup/Import Modem Config.
.. Type kbd:[1] to Setup New Modem Config.
.. Answer kbd:[Y]es to the next two questions. #FIXME#: what are they?

The following will guide you through how to set up a GGlabs GLink232-LT interface connected to BBS Server.

### GGlabs GLink232-LT

NOTE: If the BBS is configured for a Lt. Kernal, entering the modem configuration will allow you to configure not only the port your host adapter is set for, but any other ports which might be multiplexed. 

----
Enter Modem Brand/Name: GLINK232-LT
Enter Author (Return=New Image): GGLABS
Enter Custom Init String: Hit Return
What is the Max. Connection Rate For This Modem?  3
Select Hang-Up Method For This Modem: D
Auto-Answer (ATA=1): A
Use an ATH After ESCape Codes?: H
When In Local Mode, Should Phone Be: H
Does This Modem Need a 0 After ATH?: 0
Should ATH be in the Modem/Init String?: H
Select Value For ATX Setting: 1
Is DTR on This Modem Normal or Reverse?: N
Select CCITT or Bell Labs Standard: 0
Select RS232 Interface Type: 0
Is Caller ID Available (Both Modem AND Phone Line): 0
----

The BBS will create a file on the "`Etcetera Disk`" then display a Setup Completed message.
Ignore the statement about doing customized result codes. 
Then hit a key to return to the Modem Config page.
Review your settings and if any changes need to be made, type the corresponding number (such as if you want to change DTR Hang-Up to ESCape Code Hang-Up, type 2 and select E).

NOTE: If using ESCape codes, you will need to modify `sub.modem` as stated in item 6 under Installing a New System.

When finished configuring your modem, type kbd:[X] to _Exit Modem Config_ and answer `Update Modem Flags?` kbd:[Y]es.

The remaining configuration options are custom settings for your BBS and will not be discussed as part of the installation process.

## RELedit

.	Type kbd:[N] to go to the Base Editors.

.	Cursor to or type kbd:[G] for Editor Utils.

.	Type kbd:[A] to Run RELedit.
Here you will define your Subs, U/D`'s, U/X`'s and SIG`'s the same way it is done in Image 1.2a.
You _must_ define at least one SIG and add your SB, UD and UX assignments.

When finished with RELedit, exit using the kbd:[Return] key until you end up back at the Base Editor Programs Menu.

16.	The remaining items in the Base Editor Programs are Sysop Utilities for maintaining the BBS.
#TODO#: Refer to the IM Configuration Editor section for further information.

17.	Select kbd:[K] to return to the Configuration Editor.

18.	Select kbd:[Q] to exit the menu back to the Main prompt. 

19.	Refer to <<final-notes>> for further instructions.

From here, explore and become familiar with the new features. 

Much has changed since Image 1.2 and 2.0. The best way to learn is to experiment.

You`'ll probably be confused and make mistakes along the way, but the learning experience is necessary for any new system.

More information is provided in the #TODO# Sysop Guide section, but one of the main objectives of Image 3.0 is to make it as user-friendly as possible. 

As in previous versions of Image BBS software, menus are displayed with `?` and a Local Command menu is displayed to level 9 users with pseudo-Local mode access by typing `??`.

### Converting a 1.2 System

NOTE: This is the recommended way of converting 1.2 to 3.0. Other ways may work but have not been tested.

1.	Make a complete backup of all your Image 1.2 drives.
2.	You will need two new Image drives (partitions) or use two locations not already assigned as Image 1.2 drives.
They are used for your Image 3.0 "`Program Disk`" (DR5) and your 3.0 "`System Disk`" (DR1).

IMPORTANT: _Do not_ delete any of your Image 1.2 files unless otherwise told to do so.

Alternately, if you have enough hard drive space, such as on a CMD hard drive, you could make new partitions for all your Image drives and copy everything except the 1.2 boot and program drives to the new partitions. This method would allow you to revert back to 1.2 at any time in the condition it was last in.

3.	Either convert the two .d81 files to floppy disk or use some other method of getting the files onto your Image drives.

4.	Either use fcopy+ included on the 3.0 UTILITIES disk or log onto your 1.2 system in local mode and use +.CP for copying all the files from disk 1 to your NEW 3.0 "`Program Disk`".  Copy all e. files EXCEPT for the rel files from IMAGE 3.0 D2 to your "`Etcetera Disk`".

5.	Use fcopy+ or +.CP to copy all the s.files to your NEW 3.0 "`SYSTEM Disk`" and the  nm.times file to your EXISTING 1.2 mail drive.

If you want to keep your existing news files and canned message files, copy the `n.*` and `s.can*` files from your 1.2 system drive to your 3.0 "`System Disk`". 

### Edit Your `bd.data` File

1. Log on to your 1.2 system.

2. Enter the 1.2 WF editor and ``.G``et the file `bd.data` from your 1.2 boot drive.
Lines 1 through 12 identify your Image drive assignments.
3. ``.E``dit lines 1 and 2 for your new 3.0 System Disk device and drive numbers.
4. ``.E``dit lines 9 and 10 for your new 3.0 Program Disk device and drive numbers.
5. ``.E``dit any other drive assignments that may have changed. 
6. ``.L``ist the file and make sure everything is correct.
``.P``ut that as ``d.data`` (__not__ ``bd.data``) to your new 3.0 Program Disk.

7.	IMPORTANT STEP – 

8.  #FIXME#
9.  #FIXME#

10.	Scratch the file `e.last` from your 1.2 system.

Shut down your computer and reboot the BBS.

### Installation

## Duplicate Installation Instructions

NOTE: Transfer previous copy here?

a.  	The file `sub.modem` is customized for use with BBS Server using DTR as carrier detect.  Line 60080 contains print#131,chr$(27) for #lowering DTR FIXME#. If you are using a virtual modem such as tcpser and need to use escape codes for disconnecting the caller from the BBS, you may need to change the (27) to (43).
b.	The file `im` line 3082 is preconfigured for running Image 3.0 from the User port. If you intend to run from the cartridge port using a Swiftlink clone change &,16,. at the end of that line to &,16,1
c.	The file `im` line 3074 is preconfigured to run from drive 0. This is the default partition on most drives but if running on a Lt. Kernal and your boot LU is not LU0, change the `0` in line 3074 to the number of your boot LU.
1.	Turn on your computer and go to your new 3.0 "`Program Disk`". Type:  load"boot",x,1  (x= device # of your "`Program Disk`")
2.  	When prompted, type 2 to Convert from Image 1.2.
3.	Clock setting: - You are asked to select a method of setting the system clock automatically during boot up.
For this installation method, select (1) Manually. You are able to change that later during configuration.
4.	At this point, Image will create several files needed for its own operation.
It will read the Image drive assignments and access group information from `d.data` and use that information to create a new `bd.data` file on its own Program Disk, modify the existing `e.data` file with expanded 3.0 information, and create a new file called `e.access`.
When finished, Image will reboot to the System Idle screen.

### Configuration

TIP: Duplicate section. Old formatting.

1.	At the System Idle screen, hit the number 1 key to set the time. Image will perform auto maintenance and return to the Idle screen.
2.	Press the f1 key to go to full screen mode then press the f7 key to log on. Press the "`I`" key for Instant Login. 
3.	If asked, type your password. The BBS will greet you with a welcome message and then prompt you to select your time zone.
4.	Select your time zone (7=EST, 6=CST, 5=MST, 4=PST)
5.	Enter the number of lines per screen (suggest 23)
6.	At the main prompt, type EP to Edit your Parameters. 
	Select kbd:[P]arameters
	Set your Computer Type and any other Terminal Parameters you want. 
	Set Cursor Menu Mode On
	Hit RETURN to exit.
	At the main prompt, type EP to Edit your Parameters. 
	Select Info
	Change your phone number to your email address
	Hit RETURN to exit
7.	At this point, it is suggested you log off using the O command and answer Yes to Update User File? This will save your new parameters to your user file. You can then log back on in any mode you choose.

NOTE:  Always log off with the O, O! or O%! command. Logging off with the f7 key will bypass the module which updates the last 10 callers and cause errors in the time used.

8.	Log back on to the BBS. At the main prompt, type IM - You are taken to the Image BBS Configuration Editor
9.	You can use cursor controls or just type E for Access Groups. All group names and flags should be the same as your 1.2 system was. Edit any access group Name and Flags per your preference. Enter RETURN to exit, saving changes. You are returned to the Configuration Editor.
10.	Enter I for Misc. Features - At minimum, you will need to set the Time Zone and the System ID. If you are running on a Lt. Kernal, use option A to set to your Lt. K device number. Enter M to configure your Chat messages for entering and leaving chat. Edit any other parameter you wish to set.  When finished, type N to Quit back to the Configuration Editor.
11.	Enter J for Modem Config. Enter B for Setup/Import Modem Config.  Enter 1 to Setup New Modem Config.  Answer Yes to the next two questions. The following will guide you through how to set up a gglabs glink232 (or Swiftlink) modem interfaced to BBS Server:

NOTE: If the BBS is configured for a Lt. Kernal, entering the modem configuration will allow you to configure not only the port your host adapter is set for but any other ports which might be multiplexed. 

Enter Modem Brand/Name: GLINK232
Enter Author (Return=New Image): GGLABS
Enter Custom Init String: Just hit RETURN
What is the Max. Connection Rate For This Modem?  6
Select Hand-Up Method For This Modem: D
Auto-Answer (ATS)=1): A
Use an ATH After ESCape Codes?: H
When In Local Mode, Should Phone Be: H
Does This Modem Need a 0 After ATH?: 0
Should ATH be in the Modem/Init String?: H
Select Value For ATX Setting: 1
Is DTR on This Modem Normal or Reverse?: N
Select CCITT or Bell Labs Standard: 0
Select RS232 Interface Type: 1
Is Caller ID Available (Both Modem AND Phone Line): 0

The BBS will create a file on the etc drive then display a Setup Completed message. Ignore the statement about doing customized result codes. Then Hit a Key to return to the Modem Config page. Review your settings and if any changes need to be made, type the corresponding number such as if you want to change DTR Hang-Up to ESCape Code Hang-Up, type 2 and select E.

NOTE: If using ESCape codes, you will need to modify `sub.modem` as stated in item 6 under Installing a New System.

When finished configuring your modem, type X to Exit Modem Config and Yes to Update Modem Flags?
12. Enter D to go to the Logon Editor. 
13.	Type kbd:[A] for Logon Mods and type kbd:[H]elp for instructions on how to configure your logon modules.
Configure them for your preference.
Since this is a conversion from 1.2 to 3.0, I highly recommend including `i/lo-email` as a forced module in your login mods.
This will ask any user who is still configured with a phone number in their `u.config` file to change it to an email address.

14.	Enter B for Maint Mods and configure your nightly Maintenance modules.
15.	Configure any other items you need to get started.
16.	When back at the Configuration Editor, type N to go to the Base Editors.
17.	Cursor to or type G for Editor Utils.
18.	Enter A to Run RELedit. Here you should find your Subs, U/D`'s, U/X`'s and SIG`'s the same way it was configured in Image 1.2a. Verify everything is correct or make changes as needed. If your 1.2 system was networked, you will need to go into each netsub you have defined. No changes need to be made from within the netsub but when you exit each netsub, they are updated with the Image 3.0 load address for the structures type file they are stored in. When finished with RELedit, exit out using the RETURN key. The BBS will then perform a series of operations to convert all your 1.2 Sigs to 3.0 format. And end back at the Base Editor Menu.

19.	This would be a good time to check your CMD Clock and Set Time Device \# of your CMD drive if you want to use it for setting Image time during boot up. Use the available menu selections.

19.	Type kbd:[K] to quit back to the Configuration Editor.

20.	Type kbd:[Q] to quit back to the Main prompt.

21.	If you had macros defined in your 1.2 system and want to keep them, you will need to edit the `e.macros` file, otherwise, just delete it. To edit the `e.macros` file, use the RF command at the Main prompt to read the Relative File `e.data`. Read "`All`" the records to see how many macros you have defined. Then read "`e.macros`" again and view record 1. Edit record 1 by changing it to a number equal to 1 less than the total number of macros you previously viewed.
22.	Read the <<final-notes>> on the last page of these instructions.

From here, explore and become familiar with the new features. 
Much has changed since Image 1.2 and 2.0. The best way to learn is to experiment. You`'ll probably be confused and make mistakes along the way but the learning experience is necessary for any new system. More information is provided in the #TODO# Sysop Guide section but one of the main objectives of Image 3.0 is to make it as user-friendly as possible. 

As in previous versions of Image BBS software, menus are displayed with the ? mark and a Local Command menu is displayed to level 9 users with pseudo-Local mode access by entering ??.

## Converting a 2.0 System

### Installation

NOTE: bla

a.	The file `im` line 3074 is preconfigured to run from drive 0. 
This is the default partition on most drives but if running on a Lt. Kernal and your boot LU is not LU0, change the `0` in line 3074 to the number of your boot LU.

b.	This is the recommended way of converting 2.0 to 3.0.
Other ways may work but have not been tested.
Since you are already running Image 2.0, keep the same Image drive assignments for the 3.0 upgrade.

    1. Make a complete backup of all your Image 2.0 drives.
    2. Copy `bd.data` from your programs drive to your "`Etcetera Disk`".
    3. Remove all your 2.0 boot and program files from your "`Program Disk`".
4. Copy all the files from IMAGE 3.0 D1 to your "`Program Disk`".

5. Copy `bd.data` from the "`Etcetera Disk`" to the "`Program Disk`" and rename it to "`d.data`".

6. Copy `e.lightdefs`, `e.lightbar` and `e.ecs.main` from IMAGE 3.0 D2 to your "`Etcetera Disk`" replacing the existing files of the same name.
    7. Remove all the Image 2.0 s. files from your "`System Disk`".
    
CAUTION: What if you've written custom board entry files or login screens?

[start=8]
8. Copy all the s. files from IMAGE 3.0 D2 to your System Disk`".

9. If you want to run the "`Today in History`" login module in 3.0, copy all the "`today.*`" files from IMAGE 3.0 D2 to your "`Etcetera Disk`".

10. From your "`Program Disk`", type `load`"boot`",8,1` (or the Lt. Kernal or the JiffyDOS equivalent `%boot`)

11. When prompted, type kbd:[3] to _Convert a 2.0 system_.

12. Image 3.0 will perform all the necessary tasks of converting your 2.0 to 3.0 and will end up at the idle screen. Since the 3.0 modem configuration is different from 2.0, Image will not be communicating with your virtual modem.

13. Log on to your BBS from the console and enter IM to go to the Configuration Editor.

14. Configure your modem.

15. Configure any items not already configured in Misc. Features.

16. Go into the Logon Editor and configure your Login Mods. There is a Help function which will explain how to do it.

17. Configure your new Maint Mods.

18. Configure your Lightbar Defs. 

19. When back at the IM Configuration Editor, select the option for "`Base Editors`". This will take you to the menu page that used to be called by the SM command in 2.0. You shouldn’t have to do anything there but you can look around if you want to. When done, use the Quit option to go back to the Configuration Editor and Quit from there back to the Main prompt.

20. Enter NF to go to the News files and configure any news files needing to be edited, added or configured. (`n.$Welcome!`) Quit back to the Main prompt when done.

21. #Type kbd:[GF]# to go to the General Files section. Notice that nothing is configured. You will need to reconfigure your GF section due to the incompatibility of 3.0 and 2.0 program files.

From here, explore and become familiar with the new features. 

Much has changed since Image 1.2 and 2.0. The best way to learn is to experiment.
You`'ll probably be confused and make mistakes along the way but the learning experience is necessary for any new system.
More information is provided in the #TODO# Sysop Guide section but one of the main objectives of Image 3.0 is to make it as user-friendly as possible. 

As in previous versions of Image BBS software, menus are displayed with kbd:[?] and a Local Command menu is displayed to level 9 users with pseudo-Local mode access by entering kbd:[??].

## Final Notes [[final-notes]]

Included in the Image 3.0 package is a games disk containing several ready-to-install games converted to Image 3.0 format.
Load and run the `run me` file (Image SEQ Reader) which will allow you to read the installation instructions for all the games included on the disk.

Also included in the Image 3.0 package is a weed mod disk.
Load and run the `run me` file (Image Reader) which will allow you to read the installation instructions for all the files included on the disk.

In Image 3.0, the GF section replaces the Image 1.2 `PF`, `TF`, `NF` and `RF` sections.
To go there, enter kbd:[GF] at the Main prompt.
If you`'re in Maintenance Mode with Graphic Menus on, you will see a list of sysop options for editing the menus.
It was designed to be sysop friendly and anyone with a little Image 1.2 knowledge should be able to navigate through the functions to get items added to the GF section. 

These instructions were written for real hardware but Image 3.0 will run well in WinVice.
In fact, much of the development and testing of this software was done in VICE. 

Enjoy the files.
Many thousand man-hours have gone into their creation and what they are today.

I will answer questions and provide tech support for this software as needed.
Contact X-TEC at node 1 of the NISSA Network.

[.text-right]
Larry Hedman
[.text-right]
Al DeRosa
