:experimental: // enable kbd:[] macro
:icons: font

=== Typography Notes

There are several conventions used in this manual.

==== Variable Names

_Italic text_ represents a variable.

.Example
_name_

Variable names made of two words are tied together with an underscore (`_`).

.Compound Variable Name
****
``__first_name__``
****

This method differentiates _first_name_ as being separate from two variables named _first_ and _name_.

==== Highlighted Text

The highlighted words #FIXME# and #TODO# represent things in the documentation which aren't complete yet, but are intended to be finished as soon as possible.

==== Keyboard Keys and Typed Commands

Letters enclosed in rounded, shaded squares represent keys on the Commodore 64 keyboard.
They generally are either options for, or should be pressed during, a series of instructions in the manual.

.Keyboard Keys
====
kbd:[Ctrl] or kbd:[f1]: A single keypress.

kbd:[Shift+T]: Two keys with a **+** between them represent holding down the first key while typing the second key.

kbd:[.],kbd:[C]: Two keystrokes in sequence
====

.Typed Commands

The same notation can also represent BBS commands typed at a prompt.

====
* kbd:[ST], kbd:[AT], or kbd:[O!]
* Type kbd:[Y]es
====

Monospace text on a gray background usually represents output shown on the screen.

.Output or Prompt
====
 Enter your user name or ID#:
====

Bold monospace text represents text typed by the user in response to a prompt.

.Example
`Enter your user name or ID#: **45**` kbd:[Return]

==== Callouts

_Callouts_ are numbers enclosed in circles at the end of a line of instructions or text.
They provide a way to add annotations to lines below the block of text.
The numbers are not meant to be typed, but match the number below the block of text.

----

Example code <1>
More examples <2>

----
<1> A longer explanation of what the first line of code, data  or instruction does will go here.

<2> Another explanation of the next line of example code, data or instruction.

==== Icons

Icons are used to draw your attention to situations or information.
They are presented here, in order of increasing severity, with some examples from throughout the manual:

====
NOTE: **Note**

This is extra information about a topic which is considered important.

.Example
#FIXME#
====

====
TIP: **Tip**

This can be advanced information, or letting you know something helpful which isn't immediately obvious from the documentation--perhaps it's semi-hidden in a BBS module, or not presented as an option on screen.

.Example
When in the Image Term phonebook, some options such as kbd:[D]ial or kbd:[E]dit allow typing either:

* kbd:[D]ial kbd:[Return], then answer the `Dial Which` prompt with kbd:[4] kbd:[Return]

* kbd:[D4] kbd:[Return] to dial entry #4 directly
====

====
IMPORTANT: **Important**

This can be used to emphasize a point in the documentation which is

.Example
Also copy `im` to your modules disk.
If a BASIC error is caught by the error-trapping routine, the `im` module reloads from the modules disk instead of the copy on the boot drive or partition that you booted the BBS from.

Without this second copy of `im` present, your BBS may crash when an error is encountered.
====

====
CAUTION: **Caution**

Be careful here; read on-screen prompts if applicable.
Something unwanted may happen if you hurry through this section.

.Example
The Image BBS text editor currently does not confirm whether you want to clear the text buffer when you type either kbd:[.A]`bort` or kbd:[.N]`ew Text` followed by kbd:[Return].
Once you type either of these dot commands, your text will be erased.
====

====
WARNING: **Warning**

Your BBS or data could be impacted by doing something (or not) here.
The warning should contain an explanation of why doing something is harmful.

.Example
Deleting the configuration file `bd.data` requires you to reconfigure many aspects of your BBS.
====

==== Sidebars

These contain information which can be of interest to some, but is not required reading.
They look like this:

.Details: Something or Other
****
This is a deep dive into a technical issue that may be skipped over depending on the reader's interest.
****

==== Command Path

Like a search path for executables in an operating system, this gives you the location of (and steps to reach) a command.

.Command Path
====
To add sysops to the immediate logon list:

The command path is kbd:[IM], kbd:[D] `Logon Editor`, kbd:[D] `Quicklist`.
====

// this looks like a good include for the IM section:

. kbd:[IM]: type these characters at a prompt.
. kbd:[D] `Logon Editor`: A graphic menu option is selected by either:
* typing kbd:[D] to select `Logon Editor` (it`'s a _hotkey_, so hitting kbd:[Return] to select it is not necessary)
* using the cursor keys to move to `Logon Editor`, and kbd:[Return] to select it
. You would follow the same procedure for the second menu option, kbd:[D] `Quicklist`.

==== Latin Junk

Because I`'m such a nerd:

* _e.g._ is short for _exemplī grātiā_, meaning "`for example.`"

* _i.e._ is short for _id est_, meaning "`that is to say,`" or "`in other words.`"

* _per se_ (commonly misspelled as "`per say`") means "`By itself; without consideration of extraneous factors.`"
